# coding: utf-8

"""
    Encypher Enterprise API

    C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from encypher.models.sign_document import SignDocument

class TestSignDocument(unittest.TestCase):
    """SignDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignDocument:
        """Test SignDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignDocument`
        """
        model = SignDocument()
        if include_optional:
            return SignDocument(
                text = '0',
                document_id = '0',
                document_title = '',
                document_url = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return SignDocument(
                text = '0',
        )
        """

    def testSignDocument(self):
        """Test SignDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
