# coding: utf-8

"""
    Encypher Enterprise API

    C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from encypher.models.batch_item_payload import BatchItemPayload

class TestBatchItemPayload(unittest.TestCase):
    """BatchItemPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BatchItemPayload:
        """Test BatchItemPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BatchItemPayload`
        """
        model = BatchItemPayload()
        if include_optional:
            return BatchItemPayload(
                document_id = '0',
                text = '0',
                title = '',
                metadata = {
                    'key' : null
                    }
            )
        else:
            return BatchItemPayload(
                document_id = '0',
                text = '0',
        )
        """

    def testBatchItemPayload(self):
        """Test BatchItemPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
