# coding: utf-8

"""
    Encypher Enterprise API

    C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from encypher.models.document_encode_response import DocumentEncodeResponse

class TestDocumentEncodeResponse(unittest.TestCase):
    """DocumentEncodeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentEncodeResponse:
        """Test DocumentEncodeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentEncodeResponse`
        """
        model = DocumentEncodeResponse()
        if include_optional:
            return DocumentEncodeResponse(
                success = True,
                message = '',
                document_id = '',
                organization_id = '',
                roots = {
                    'key' : encypher.models.merkle_root_response.MerkleRootResponse(
                        root_id = '', 
                        document_id = '', 
                        root_hash = '', 
                        tree_depth = 56, 
                        total_leaves = 56, 
                        segmentation_level = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = {
                            'key' : null
                            }, )
                    },
                total_segments = {
                    'key' : 56
                    },
                processing_time_ms = 1.337,
                fuzzy_index = {
                    'key' : null
                    }
            )
        else:
            return DocumentEncodeResponse(
                success = True,
                message = '',
                document_id = '',
                organization_id = '',
                roots = {
                    'key' : encypher.models.merkle_root_response.MerkleRootResponse(
                        root_id = '', 
                        document_id = '', 
                        root_hash = '', 
                        tree_depth = 56, 
                        total_leaves = 56, 
                        segmentation_level = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        metadata = {
                            'key' : null
                            }, )
                    },
                total_segments = {
                    'key' : 56
                    },
                processing_time_ms = 1.337,
        )
        """

    def testDocumentEncodeResponse(self):
        """Test DocumentEncodeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
