# coding: utf-8

"""
    Encypher Enterprise API

    C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

    The version of the OpenAPI document: 1.0.0-preview
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from encypher.models.audit_log_entry import AuditLogEntry

class TestAuditLogEntry(unittest.TestCase):
    """AuditLogEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuditLogEntry:
        """Test AuditLogEntry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuditLogEntry`
        """
        model = AuditLogEntry()
        if include_optional:
            return AuditLogEntry(
                id = '',
                timestamp = '',
                action = '',
                actor_id = '',
                actor_type = '',
                resource_type = '',
                resource_id = '',
                details = {
                    'key' : null
                    },
                ip_address = '',
                user_agent = ''
            )
        else:
            return AuditLogEntry(
                id = '',
                timestamp = '',
                action = '',
                actor_id = '',
                actor_type = '',
                resource_type = '',
        )
        """

    def testAuditLogEntry(self):
        """Test AuditLogEntry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
