/* tslint:disable */
/* eslint-disable */
/**
 * Encypher Enterprise API
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  KeyCreateRequest,
  KeyCreateResponse,
  KeyListResponse,
  KeyRevokeResponse,
  KeyRotateResponse,
  KeyUpdateRequest,
  KeyUpdateResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    KeyCreateRequestFromJSON,
    KeyCreateRequestToJSON,
    KeyCreateResponseFromJSON,
    KeyCreateResponseToJSON,
    KeyListResponseFromJSON,
    KeyListResponseToJSON,
    KeyRevokeResponseFromJSON,
    KeyRevokeResponseToJSON,
    KeyRotateResponseFromJSON,
    KeyRotateResponseToJSON,
    KeyUpdateRequestFromJSON,
    KeyUpdateRequestToJSON,
    KeyUpdateResponseFromJSON,
    KeyUpdateResponseToJSON,
} from '../models/index';

export interface CreateKeyApiV1KeysPostRequest {
    keyCreateRequest: KeyCreateRequest;
}

export interface CreateKeyApiV1KeysPost0Request {
    keyCreateRequest: KeyCreateRequest;
}

export interface ListKeysApiV1KeysGetRequest {
    includeRevoked?: boolean;
}

export interface ListKeysApiV1KeysGet0Request {
    includeRevoked?: boolean;
}

export interface RevokeKeyApiV1KeysKeyIdDeleteRequest {
    keyId: string;
}

export interface RevokeKeyApiV1KeysKeyIdDelete0Request {
    keyId: string;
}

export interface RotateKeyApiV1KeysKeyIdRotatePostRequest {
    keyId: string;
}

export interface RotateKeyApiV1KeysKeyIdRotatePost0Request {
    keyId: string;
}

export interface UpdateKeyApiV1KeysKeyIdPatchRequest {
    keyId: string;
    keyUpdateRequest: KeyUpdateRequest;
}

export interface UpdateKeyApiV1KeysKeyIdPatch0Request {
    keyId: string;
    keyUpdateRequest: KeyUpdateRequest;
}

/**
 * APIKeysApi - interface
 * 
 * @export
 * @interface APIKeysApiInterface
 */
export interface APIKeysApiInterface {
    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * @summary Create Key
     * @param {KeyCreateRequest} keyCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    createKeyApiV1KeysPostRaw(requestParameters: CreateKeyApiV1KeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyCreateResponse>>;

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    createKeyApiV1KeysPost(requestParameters: CreateKeyApiV1KeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyCreateResponse>;

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * @summary Create Key
     * @param {KeyCreateRequest} keyCreateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    createKeyApiV1KeysPost_1Raw(requestParameters: CreateKeyApiV1KeysPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyCreateResponse>>;

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    createKeyApiV1KeysPost_1(requestParameters: CreateKeyApiV1KeysPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyCreateResponse>;

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * @summary List Keys
     * @param {boolean} [includeRevoked] Include revoked keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    listKeysApiV1KeysGetRaw(requestParameters: ListKeysApiV1KeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyListResponse>>;

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    listKeysApiV1KeysGet(requestParameters: ListKeysApiV1KeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyListResponse>;

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * @summary List Keys
     * @param {boolean} [includeRevoked] Include revoked keys
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    listKeysApiV1KeysGet_2Raw(requestParameters: ListKeysApiV1KeysGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyListResponse>>;

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    listKeysApiV1KeysGet_2(requestParameters: ListKeysApiV1KeysGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyListResponse>;

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * @summary Revoke Key
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    revokeKeyApiV1KeysKeyIdDeleteRaw(requestParameters: RevokeKeyApiV1KeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRevokeResponse>>;

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    revokeKeyApiV1KeysKeyIdDelete(requestParameters: RevokeKeyApiV1KeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRevokeResponse>;

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * @summary Revoke Key
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    revokeKeyApiV1KeysKeyIdDelete_3Raw(requestParameters: RevokeKeyApiV1KeysKeyIdDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRevokeResponse>>;

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    revokeKeyApiV1KeysKeyIdDelete_3(requestParameters: RevokeKeyApiV1KeysKeyIdDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRevokeResponse>;

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * @summary Rotate Key
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    rotateKeyApiV1KeysKeyIdRotatePostRaw(requestParameters: RotateKeyApiV1KeysKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRotateResponse>>;

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    rotateKeyApiV1KeysKeyIdRotatePost(requestParameters: RotateKeyApiV1KeysKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRotateResponse>;

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * @summary Rotate Key
     * @param {string} keyId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    rotateKeyApiV1KeysKeyIdRotatePost_4Raw(requestParameters: RotateKeyApiV1KeysKeyIdRotatePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRotateResponse>>;

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    rotateKeyApiV1KeysKeyIdRotatePost_4(requestParameters: RotateKeyApiV1KeysKeyIdRotatePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRotateResponse>;

    /**
     * Update an API key\'s name or permissions.
     * @summary Update Key
     * @param {string} keyId 
     * @param {KeyUpdateRequest} keyUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    updateKeyApiV1KeysKeyIdPatchRaw(requestParameters: UpdateKeyApiV1KeysKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyUpdateResponse>>;

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    updateKeyApiV1KeysKeyIdPatch(requestParameters: UpdateKeyApiV1KeysKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyUpdateResponse>;

    /**
     * Update an API key\'s name or permissions.
     * @summary Update Key
     * @param {string} keyId 
     * @param {KeyUpdateRequest} keyUpdateRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof APIKeysApiInterface
     */
    updateKeyApiV1KeysKeyIdPatch_5Raw(requestParameters: UpdateKeyApiV1KeysKeyIdPatch0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyUpdateResponse>>;

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    updateKeyApiV1KeysKeyIdPatch_5(requestParameters: UpdateKeyApiV1KeysKeyIdPatch0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyUpdateResponse>;

}

/**
 * 
 */
export class APIKeysApi extends runtime.BaseAPI implements APIKeysApiInterface {

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    async createKeyApiV1KeysPostRaw(requestParameters: CreateKeyApiV1KeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyCreateResponse>> {
        if (requestParameters['keyCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'keyCreateRequest',
                'Required parameter "keyCreateRequest" was null or undefined when calling createKeyApiV1KeysPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KeyCreateRequestToJSON(requestParameters['keyCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    async createKeyApiV1KeysPost(requestParameters: CreateKeyApiV1KeysPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyCreateResponse> {
        const response = await this.createKeyApiV1KeysPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    async createKeyApiV1KeysPost_1Raw(requestParameters: CreateKeyApiV1KeysPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyCreateResponse>> {
        if (requestParameters['keyCreateRequest'] == null) {
            throw new runtime.RequiredError(
                'keyCreateRequest',
                'Required parameter "keyCreateRequest" was null or undefined when calling createKeyApiV1KeysPost_1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: KeyCreateRequestToJSON(requestParameters['keyCreateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyCreateResponseFromJSON(jsonValue));
    }

    /**
     * Create a new API key.  The full key is only returned once - store it securely.
     * Create Key
     */
    async createKeyApiV1KeysPost_1(requestParameters: CreateKeyApiV1KeysPost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyCreateResponse> {
        const response = await this.createKeyApiV1KeysPost_1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    async listKeysApiV1KeysGetRaw(requestParameters: ListKeysApiV1KeysGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['includeRevoked'] != null) {
            queryParameters['include_revoked'] = requestParameters['includeRevoked'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyListResponseFromJSON(jsonValue));
    }

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    async listKeysApiV1KeysGet(requestParameters: ListKeysApiV1KeysGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyListResponse> {
        const response = await this.listKeysApiV1KeysGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    async listKeysApiV1KeysGet_2Raw(requestParameters: ListKeysApiV1KeysGet0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyListResponse>> {
        const queryParameters: any = {};

        if (requestParameters['includeRevoked'] != null) {
            queryParameters['include_revoked'] = requestParameters['includeRevoked'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyListResponseFromJSON(jsonValue));
    }

    /**
     * List API keys for the organization.  Keys are masked - only the prefix is shown for security.
     * List Keys
     */
    async listKeysApiV1KeysGet_2(requestParameters: ListKeysApiV1KeysGet0Request = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyListResponse> {
        const response = await this.listKeysApiV1KeysGet_2Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    async revokeKeyApiV1KeysKeyIdDeleteRaw(requestParameters: RevokeKeyApiV1KeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRevokeResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling revokeKeyApiV1KeysKeyIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyRevokeResponseFromJSON(jsonValue));
    }

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    async revokeKeyApiV1KeysKeyIdDelete(requestParameters: RevokeKeyApiV1KeysKeyIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRevokeResponse> {
        const response = await this.revokeKeyApiV1KeysKeyIdDeleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    async revokeKeyApiV1KeysKeyIdDelete_3Raw(requestParameters: RevokeKeyApiV1KeysKeyIdDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRevokeResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling revokeKeyApiV1KeysKeyIdDelete_3().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyRevokeResponseFromJSON(jsonValue));
    }

    /**
     * Revoke an API key.  The key will immediately stop working. This action cannot be undone.
     * Revoke Key
     */
    async revokeKeyApiV1KeysKeyIdDelete_3(requestParameters: RevokeKeyApiV1KeysKeyIdDelete0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRevokeResponse> {
        const response = await this.revokeKeyApiV1KeysKeyIdDelete_3Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    async rotateKeyApiV1KeysKeyIdRotatePostRaw(requestParameters: RotateKeyApiV1KeysKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRotateResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling rotateKeyApiV1KeysKeyIdRotatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}/rotate`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyRotateResponseFromJSON(jsonValue));
    }

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    async rotateKeyApiV1KeysKeyIdRotatePost(requestParameters: RotateKeyApiV1KeysKeyIdRotatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRotateResponse> {
        const response = await this.rotateKeyApiV1KeysKeyIdRotatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    async rotateKeyApiV1KeysKeyIdRotatePost_4Raw(requestParameters: RotateKeyApiV1KeysKeyIdRotatePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyRotateResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling rotateKeyApiV1KeysKeyIdRotatePost_4().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}/rotate`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyRotateResponseFromJSON(jsonValue));
    }

    /**
     * Rotate an API key.  Creates a new key with the same permissions and revokes the old one. The new key is only returned once - store it securely.
     * Rotate Key
     */
    async rotateKeyApiV1KeysKeyIdRotatePost_4(requestParameters: RotateKeyApiV1KeysKeyIdRotatePost0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyRotateResponse> {
        const response = await this.rotateKeyApiV1KeysKeyIdRotatePost_4Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    async updateKeyApiV1KeysKeyIdPatchRaw(requestParameters: UpdateKeyApiV1KeysKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyUpdateResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling updateKeyApiV1KeysKeyIdPatch().'
            );
        }

        if (requestParameters['keyUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'keyUpdateRequest',
                'Required parameter "keyUpdateRequest" was null or undefined when calling updateKeyApiV1KeysKeyIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: KeyUpdateRequestToJSON(requestParameters['keyUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    async updateKeyApiV1KeysKeyIdPatch(requestParameters: UpdateKeyApiV1KeysKeyIdPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyUpdateResponse> {
        const response = await this.updateKeyApiV1KeysKeyIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    async updateKeyApiV1KeysKeyIdPatch_5Raw(requestParameters: UpdateKeyApiV1KeysKeyIdPatch0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<KeyUpdateResponse>> {
        if (requestParameters['keyId'] == null) {
            throw new runtime.RequiredError(
                'keyId',
                'Required parameter "keyId" was null or undefined when calling updateKeyApiV1KeysKeyIdPatch_5().'
            );
        }

        if (requestParameters['keyUpdateRequest'] == null) {
            throw new runtime.RequiredError(
                'keyUpdateRequest',
                'Required parameter "keyUpdateRequest" was null or undefined when calling updateKeyApiV1KeysKeyIdPatch_5().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("HTTPBearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/v1/keys/{key_id}`;
        urlPath = urlPath.replace(`{${"key_id"}}`, encodeURIComponent(String(requestParameters['keyId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: KeyUpdateRequestToJSON(requestParameters['keyUpdateRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => KeyUpdateResponseFromJSON(jsonValue));
    }

    /**
     * Update an API key\'s name or permissions.
     * Update Key
     */
    async updateKeyApiV1KeysKeyIdPatch_5(requestParameters: UpdateKeyApiV1KeysKeyIdPatch0Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<KeyUpdateResponse> {
        const response = await this.updateKeyApiV1KeysKeyIdPatch_5Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
