import pytest
from encypher.core.unicode_metadata import UnicodeMetadata


def _get_assertion_payload(assertions: list[dict], label: str) -> dict | None:
    for assertion in assertions:
        if assertion.get("label") == label:
            return assertion
    return None


@pytest.mark.asyncio
async def test_sign_advanced_minimal_uuid_c2pa_conformance(async_client, auth_headers: dict) -> None:
    response = await async_client.post(
        "/api/v1/sign",
        headers=auth_headers,
        json={
            "text": "Sentence one. Sentence two.",
            "options": {
                "manifest_mode": "minimal_uuid",
            },
        },
    )

    assert response.status_code == 201
    payload = response.json()
    # Unified response: data.document.signed_text
    data = payload.get("data", {})
    document = data.get("document", {})
    embedded_content = document.get("signed_text")

    extracted = UnicodeMetadata.extract_metadata(embedded_content)
    assert extracted is not None
    assert extracted.get("@context") == "https://c2pa.org/schemas/v2.3/c2pa.jsonld"
    assert extracted.get("claim_label") == "c2pa.claim.v2"

    assertions = extracted.get("assertions")
    assert isinstance(assertions, list)

    actions_assertion = _get_assertion_payload(assertions, "c2pa.actions.v2")
    assert actions_assertion is not None
    actions = actions_assertion.get("data", {}).get("actions", [])
    action_labels = {action.get("label") for action in actions}
    assert "c2pa.created" in action_labels
    assert "c2pa.watermarked" in action_labels

    metadata_assertion = _get_assertion_payload(assertions, "c2pa.metadata")
    assert metadata_assertion is not None
    metadata = metadata_assertion.get("data", {})
    assert metadata.get("@context") == "https://schema.org"
    # Document ID is auto-generated by unified endpoint
    assert metadata.get("identifier") is not None
    assert "manifest_mode" not in metadata


@pytest.mark.asyncio
async def test_extract_and_verify_includes_c2pa_conformance_metadata(async_client, auth_headers: dict) -> None:
    """Test that signed content can be verified and includes C2PA metadata."""
    response = await async_client.post(
        "/api/v1/sign",
        headers=auth_headers,
        json={
            "text": "Sentence one. Sentence two.",
            "options": {
                "manifest_mode": "minimal_uuid",
            },
        },
    )

    assert response.status_code == 201
    payload = response.json()
    data = payload.get("data", {})
    document = data.get("document", {})
    embedded_content = document.get("signed_text")
    assert embedded_content is not None

    # Use /verify/advanced instead of deprecated /public/extract-and-verify
    verify_response = await async_client.post(
        "/api/v1/verify/advanced",
        headers=auth_headers,
        json={"text": embedded_content},
    )

    assert verify_response.status_code == 200
    verify_payload = verify_response.json()
    assert verify_payload["success"] is True
    verdict = verify_payload.get("data", {})
    # Verify that the content was successfully verified
    assert verdict.get("valid") is True or verdict.get("embeddings_found") is True


@pytest.mark.asyncio
async def test_c2pa_manifest_does_not_leak_internal_details(async_client, auth_headers: dict) -> None:
    """TEAM_175 regression: the C2PA manifest embedded in signed content must
    not expose internal org IDs or embedding method names."""
    response = await async_client.post(
        "/api/v1/sign",
        headers=auth_headers,
        json={
            "text": "First sentence. Second sentence. Third sentence.",
            "options": {
                "manifest_mode": "micro",
                "segmentation_level": "sentence",
            },
        },
    )

    assert response.status_code == 201
    data = response.json().get("data", {})
    document = data.get("document", {})
    embedded_content = document.get("signed_text") or data.get("embedded_content")
    assert embedded_content is not None

    extracted = UnicodeMetadata.extract_metadata(embedded_content)
    assert extracted is not None

    assertions = extracted.get("assertions", [])

    # --- c2pa.metadata must not contain manifest_mode ---
    metadata_assertion = _get_assertion_payload(assertions, "c2pa.metadata")
    assert metadata_assertion is not None
    metadata = metadata_assertion.get("data", {})
    assert "manifest_mode" not in metadata, "manifest_mode should not be in public manifest"

    # --- publisher.identifier must use org name, not org_xxx ID ---
    publisher = metadata.get("publisher", {})
    publisher_id = publisher.get("identifier", "")
    assert not publisher_id.startswith("org_"), (
        f"publisher.identifier should be org name, not internal ID: {publisher_id}"
    )

    # --- c2pa.created softwareAgent must not contain org ID ---
    actions_assertion = _get_assertion_payload(assertions, "c2pa.actions.v2")
    assert actions_assertion is not None
    for action in actions_assertion.get("data", {}).get("actions", []):
        agent = action.get("softwareAgent", "")
        assert "org_" not in agent, (
            f"softwareAgent should not contain org ID: {agent}"
        )
