/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.0-preview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type StreamingAPI interface {

	/*
	CloseStreamingSessionApiV1StreamSessionSessionIdClosePost Close Streaming Session

	Close a streaming session.

Args:
    session_id: Session identifier
    organization: Authenticated organization
    db: Database session
    
Returns:
    Session closure result with stats

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param sessionId
	@return ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest
	*/
	CloseStreamingSessionApiV1StreamSessionSessionIdClosePost(ctx context.Context, sessionId string) ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest

	// CloseStreamingSessionApiV1StreamSessionSessionIdClosePostExecute executes the request
	//  @return interface{}
	CloseStreamingSessionApiV1StreamSessionSessionIdClosePostExecute(r ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest) (interface{}, *http.Response, error)

	/*
	CreateStreamingSessionApiV1StreamSessionCreatePost Create Streaming Session

	Create a new streaming session.

Args:
    session_type: Type of session (websocket, sse, kafka)
    metadata: Optional session metadata
    signing_options: Optional signing configuration
    organization: Authenticated organization
    db: Database session
    
Returns:
    Session creation result with session_id

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest
	*/
	CreateStreamingSessionApiV1StreamSessionCreatePost(ctx context.Context) ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest

	// CreateStreamingSessionApiV1StreamSessionCreatePostExecute executes the request
	//  @return interface{}
	CreateStreamingSessionApiV1StreamSessionCreatePostExecute(r ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest) (interface{}, *http.Response, error)

	/*
	GetStreamRunApiV1StreamRunsRunIdGet Get Stream Run

	Return persisted streaming run state.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param runId
	@return ApiGetStreamRunApiV1StreamRunsRunIdGetRequest
	*/
	GetStreamRunApiV1StreamRunsRunIdGet(ctx context.Context, runId string) ApiGetStreamRunApiV1StreamRunsRunIdGetRequest

	// GetStreamRunApiV1StreamRunsRunIdGetExecute executes the request
	//  @return interface{}
	GetStreamRunApiV1StreamRunsRunIdGetExecute(r ApiGetStreamRunApiV1StreamRunsRunIdGetRequest) (interface{}, *http.Response, error)

	/*
	GetStreamingStatsApiV1StreamStatsGet Get Streaming Stats

	Get streaming statistics for organization.

Args:
    organization: Authenticated organization
    
Returns:
    Streaming statistics

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiGetStreamingStatsApiV1StreamStatsGetRequest
	*/
	GetStreamingStatsApiV1StreamStatsGet(ctx context.Context) ApiGetStreamingStatsApiV1StreamStatsGetRequest

	// GetStreamingStatsApiV1StreamStatsGetExecute executes the request
	//  @return interface{}
	GetStreamingStatsApiV1StreamStatsGetExecute(r ApiGetStreamingStatsApiV1StreamStatsGetRequest) (interface{}, *http.Response, error)

	/*
	SseEventsEndpointApiV1StreamEventsGet Sse Events Endpoint

	Server-Sent Events (SSE) endpoint for unidirectional streaming.

Args:
    session_id: Session identifier
    api_key: API key for authentication
    
Returns:
    StreamingResponse with SSE events

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiSseEventsEndpointApiV1StreamEventsGetRequest
	*/
	SseEventsEndpointApiV1StreamEventsGet(ctx context.Context) ApiSseEventsEndpointApiV1StreamEventsGetRequest

	// SseEventsEndpointApiV1StreamEventsGetExecute executes the request
	//  @return interface{}
	SseEventsEndpointApiV1StreamEventsGetExecute(r ApiSseEventsEndpointApiV1StreamEventsGetRequest) (interface{}, *http.Response, error)

	/*
	StreamSigningApiV1StreamSignPost Stream Signing

	Stream signing progress via SSE.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiStreamSigningApiV1StreamSignPostRequest
	*/
	StreamSigningApiV1StreamSignPost(ctx context.Context) ApiStreamSigningApiV1StreamSignPostRequest

	// StreamSigningApiV1StreamSignPostExecute executes the request
	StreamSigningApiV1StreamSignPostExecute(r ApiStreamSigningApiV1StreamSignPostRequest) (*http.Response, error)

	/*
	StreamingHealthCheckApiV1StreamHealthGet Streaming Health Check

	Health check endpoint for streaming service.

Returns:
    Health status of streaming components

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiStreamingHealthCheckApiV1StreamHealthGetRequest
	*/
	StreamingHealthCheckApiV1StreamHealthGet(ctx context.Context) ApiStreamingHealthCheckApiV1StreamHealthGetRequest

	// StreamingHealthCheckApiV1StreamHealthGetExecute executes the request
	//  @return interface{}
	StreamingHealthCheckApiV1StreamHealthGetExecute(r ApiStreamingHealthCheckApiV1StreamHealthGetRequest) (interface{}, *http.Response, error)
}

// StreamingAPIService StreamingAPI service
type StreamingAPIService service

type ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest struct {
	ctx context.Context
	ApiService StreamingAPI
	sessionId string
}

func (r ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.CloseStreamingSessionApiV1StreamSessionSessionIdClosePostExecute(r)
}

/*
CloseStreamingSessionApiV1StreamSessionSessionIdClosePost Close Streaming Session

Close a streaming session.

Args:
    session_id: Session identifier
    organization: Authenticated organization
    db: Database session
    
Returns:
    Session closure result with stats

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param sessionId
 @return ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest
*/
func (a *StreamingAPIService) CloseStreamingSessionApiV1StreamSessionSessionIdClosePost(ctx context.Context, sessionId string) ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest {
	return ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest{
		ApiService: a,
		ctx: ctx,
		sessionId: sessionId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) CloseStreamingSessionApiV1StreamSessionSessionIdClosePostExecute(r ApiCloseStreamingSessionApiV1StreamSessionSessionIdClosePostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.CloseStreamingSessionApiV1StreamSessionSessionIdClosePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/session/{session_id}/close"
	localVarPath = strings.Replace(localVarPath, "{"+"session_id"+"}", url.PathEscape(parameterValueToString(r.sessionId, "sessionId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest struct {
	ctx context.Context
	ApiService StreamingAPI
	sessionType *string
	bodyCreateStreamingSessionApiV1StreamSessionCreatePost *BodyCreateStreamingSessionApiV1StreamSessionCreatePost
}

func (r ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest) SessionType(sessionType string) ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest {
	r.sessionType = &sessionType
	return r
}

func (r ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest) BodyCreateStreamingSessionApiV1StreamSessionCreatePost(bodyCreateStreamingSessionApiV1StreamSessionCreatePost BodyCreateStreamingSessionApiV1StreamSessionCreatePost) ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest {
	r.bodyCreateStreamingSessionApiV1StreamSessionCreatePost = &bodyCreateStreamingSessionApiV1StreamSessionCreatePost
	return r
}

func (r ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.CreateStreamingSessionApiV1StreamSessionCreatePostExecute(r)
}

/*
CreateStreamingSessionApiV1StreamSessionCreatePost Create Streaming Session

Create a new streaming session.

Args:
    session_type: Type of session (websocket, sse, kafka)
    metadata: Optional session metadata
    signing_options: Optional signing configuration
    organization: Authenticated organization
    db: Database session
    
Returns:
    Session creation result with session_id

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest
*/
func (a *StreamingAPIService) CreateStreamingSessionApiV1StreamSessionCreatePost(ctx context.Context) ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest {
	return ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) CreateStreamingSessionApiV1StreamSessionCreatePostExecute(r ApiCreateStreamingSessionApiV1StreamSessionCreatePostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.CreateStreamingSessionApiV1StreamSessionCreatePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/session/create"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	if r.sessionType != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "session_type", r.sessionType, "form", "")
	} else {
        var defaultValue string = "websocket"
        parameterAddToHeaderOrQuery(localVarQueryParams, "session_type", defaultValue, "form", "")
        r.sessionType = &defaultValue
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.bodyCreateStreamingSessionApiV1StreamSessionCreatePost
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetStreamRunApiV1StreamRunsRunIdGetRequest struct {
	ctx context.Context
	ApiService StreamingAPI
	runId string
}

func (r ApiGetStreamRunApiV1StreamRunsRunIdGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetStreamRunApiV1StreamRunsRunIdGetExecute(r)
}

/*
GetStreamRunApiV1StreamRunsRunIdGet Get Stream Run

Return persisted streaming run state.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param runId
 @return ApiGetStreamRunApiV1StreamRunsRunIdGetRequest
*/
func (a *StreamingAPIService) GetStreamRunApiV1StreamRunsRunIdGet(ctx context.Context, runId string) ApiGetStreamRunApiV1StreamRunsRunIdGetRequest {
	return ApiGetStreamRunApiV1StreamRunsRunIdGetRequest{
		ApiService: a,
		ctx: ctx,
		runId: runId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) GetStreamRunApiV1StreamRunsRunIdGetExecute(r ApiGetStreamRunApiV1StreamRunsRunIdGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.GetStreamRunApiV1StreamRunsRunIdGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/runs/{run_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"run_id"+"}", url.PathEscape(parameterValueToString(r.runId, "runId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetStreamingStatsApiV1StreamStatsGetRequest struct {
	ctx context.Context
	ApiService StreamingAPI
}

func (r ApiGetStreamingStatsApiV1StreamStatsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.GetStreamingStatsApiV1StreamStatsGetExecute(r)
}

/*
GetStreamingStatsApiV1StreamStatsGet Get Streaming Stats

Get streaming statistics for organization.

Args:
    organization: Authenticated organization
    
Returns:
    Streaming statistics

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiGetStreamingStatsApiV1StreamStatsGetRequest
*/
func (a *StreamingAPIService) GetStreamingStatsApiV1StreamStatsGet(ctx context.Context) ApiGetStreamingStatsApiV1StreamStatsGetRequest {
	return ApiGetStreamingStatsApiV1StreamStatsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) GetStreamingStatsApiV1StreamStatsGetExecute(r ApiGetStreamingStatsApiV1StreamStatsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.GetStreamingStatsApiV1StreamStatsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/stats"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiSseEventsEndpointApiV1StreamEventsGetRequest struct {
	ctx context.Context
	ApiService StreamingAPI
	sessionId *string
	apiKey *string
}

func (r ApiSseEventsEndpointApiV1StreamEventsGetRequest) SessionId(sessionId string) ApiSseEventsEndpointApiV1StreamEventsGetRequest {
	r.sessionId = &sessionId
	return r
}

func (r ApiSseEventsEndpointApiV1StreamEventsGetRequest) ApiKey(apiKey string) ApiSseEventsEndpointApiV1StreamEventsGetRequest {
	r.apiKey = &apiKey
	return r
}

func (r ApiSseEventsEndpointApiV1StreamEventsGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.SseEventsEndpointApiV1StreamEventsGetExecute(r)
}

/*
SseEventsEndpointApiV1StreamEventsGet Sse Events Endpoint

Server-Sent Events (SSE) endpoint for unidirectional streaming.

Args:
    session_id: Session identifier
    api_key: API key for authentication
    
Returns:
    StreamingResponse with SSE events

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiSseEventsEndpointApiV1StreamEventsGetRequest
*/
func (a *StreamingAPIService) SseEventsEndpointApiV1StreamEventsGet(ctx context.Context) ApiSseEventsEndpointApiV1StreamEventsGetRequest {
	return ApiSseEventsEndpointApiV1StreamEventsGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) SseEventsEndpointApiV1StreamEventsGetExecute(r ApiSseEventsEndpointApiV1StreamEventsGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.SseEventsEndpointApiV1StreamEventsGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/events"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.sessionId == nil {
		return localVarReturnValue, nil, reportError("sessionId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "session_id", r.sessionId, "form", "")
	if r.apiKey != nil {
		parameterAddToHeaderOrQuery(localVarQueryParams, "api_key", r.apiKey, "form", "")
	}
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiStreamSigningApiV1StreamSignPostRequest struct {
	ctx context.Context
	ApiService StreamingAPI
	streamSignRequest *StreamSignRequest
}

func (r ApiStreamSigningApiV1StreamSignPostRequest) StreamSignRequest(streamSignRequest StreamSignRequest) ApiStreamSigningApiV1StreamSignPostRequest {
	r.streamSignRequest = &streamSignRequest
	return r
}

func (r ApiStreamSigningApiV1StreamSignPostRequest) Execute() (*http.Response, error) {
	return r.ApiService.StreamSigningApiV1StreamSignPostExecute(r)
}

/*
StreamSigningApiV1StreamSignPost Stream Signing

Stream signing progress via SSE.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiStreamSigningApiV1StreamSignPostRequest
*/
func (a *StreamingAPIService) StreamSigningApiV1StreamSignPost(ctx context.Context) ApiStreamSigningApiV1StreamSignPostRequest {
	return ApiStreamSigningApiV1StreamSignPostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
func (a *StreamingAPIService) StreamSigningApiV1StreamSignPostExecute(r ApiStreamSigningApiV1StreamSignPostRequest) (*http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.StreamSigningApiV1StreamSignPost")
	if err != nil {
		return nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/sign"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.streamSignRequest == nil {
		return nil, reportError("streamSignRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.streamSignRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarHTTPResponse, newErr
	}

	return localVarHTTPResponse, nil
}

type ApiStreamingHealthCheckApiV1StreamHealthGetRequest struct {
	ctx context.Context
	ApiService StreamingAPI
}

func (r ApiStreamingHealthCheckApiV1StreamHealthGetRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.StreamingHealthCheckApiV1StreamHealthGetExecute(r)
}

/*
StreamingHealthCheckApiV1StreamHealthGet Streaming Health Check

Health check endpoint for streaming service.

Returns:
    Health status of streaming components

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiStreamingHealthCheckApiV1StreamHealthGetRequest
*/
func (a *StreamingAPIService) StreamingHealthCheckApiV1StreamHealthGet(ctx context.Context) ApiStreamingHealthCheckApiV1StreamHealthGetRequest {
	return ApiStreamingHealthCheckApiV1StreamHealthGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *StreamingAPIService) StreamingHealthCheckApiV1StreamHealthGetExecute(r ApiStreamingHealthCheckApiV1StreamHealthGetRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "StreamingAPIService.StreamingHealthCheckApiV1StreamHealthGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/stream/health"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
