/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.0-preview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"bytes"
	"context"
	"io"
	"net/http"
	"net/url"
	"strings"
)


type TeamManagementAPI interface {

	/*
	AcceptInviteApiV1OrgMembersAcceptInvitePost Accept Invite

	Accept a team invitation.

This endpoint is called after the user authenticates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest
	*/
	AcceptInviteApiV1OrgMembersAcceptInvitePost(ctx context.Context) ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest

	// AcceptInviteApiV1OrgMembersAcceptInvitePostExecute executes the request
	//  @return interface{}
	AcceptInviteApiV1OrgMembersAcceptInvitePostExecute(r ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest) (interface{}, *http.Response, error)

	/*
	AcceptInviteApiV1OrgMembersAcceptInvitePost_0 Accept Invite

	Accept a team invitation.

This endpoint is called after the user authenticates.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request
	*/
	AcceptInviteApiV1OrgMembersAcceptInvitePost_1(ctx context.Context) ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request

	// AcceptInviteApiV1OrgMembersAcceptInvitePost_1Execute executes the request
	//  @return interface{}
	AcceptInviteApiV1OrgMembersAcceptInvitePost_1Execute(r ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request) (interface{}, *http.Response, error)

	/*
	InviteMemberApiV1OrgMembersInvitePost Invite Member

	Invite a new member to the organization.

Sends an email invitation that expires in 7 days.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiInviteMemberApiV1OrgMembersInvitePostRequest
	*/
	InviteMemberApiV1OrgMembersInvitePost(ctx context.Context) ApiInviteMemberApiV1OrgMembersInvitePostRequest

	// InviteMemberApiV1OrgMembersInvitePostExecute executes the request
	//  @return InviteResponse
	InviteMemberApiV1OrgMembersInvitePostExecute(r ApiInviteMemberApiV1OrgMembersInvitePostRequest) (*InviteResponse, *http.Response, error)

	/*
	InviteMemberApiV1OrgMembersInvitePost_0 Invite Member

	Invite a new member to the organization.

Sends an email invitation that expires in 7 days.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiInviteMemberApiV1OrgMembersInvitePost_0Request
	*/
	InviteMemberApiV1OrgMembersInvitePost_2(ctx context.Context) ApiInviteMemberApiV1OrgMembersInvitePost_0Request

	// InviteMemberApiV1OrgMembersInvitePost_2Execute executes the request
	//  @return InviteResponse
	InviteMemberApiV1OrgMembersInvitePost_2Execute(r ApiInviteMemberApiV1OrgMembersInvitePost_0Request) (*InviteResponse, *http.Response, error)

	/*
	ListPendingInvitesApiV1OrgMembersInvitesGet List Pending Invites

	List all pending invitations.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest
	*/
	ListPendingInvitesApiV1OrgMembersInvitesGet(ctx context.Context) ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest

	// ListPendingInvitesApiV1OrgMembersInvitesGetExecute executes the request
	//  @return []PendingInvite
	ListPendingInvitesApiV1OrgMembersInvitesGetExecute(r ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest) ([]PendingInvite, *http.Response, error)

	/*
	ListPendingInvitesApiV1OrgMembersInvitesGet_0 List Pending Invites

	List all pending invitations.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request
	*/
	ListPendingInvitesApiV1OrgMembersInvitesGet_3(ctx context.Context) ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request

	// ListPendingInvitesApiV1OrgMembersInvitesGet_3Execute executes the request
	//  @return []PendingInvite
	ListPendingInvitesApiV1OrgMembersInvitesGet_3Execute(r ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request) ([]PendingInvite, *http.Response, error)

	/*
	ListTeamMembersApiV1OrgMembersGet List Team Members

	List all team members in the organization.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListTeamMembersApiV1OrgMembersGetRequest
	*/
	ListTeamMembersApiV1OrgMembersGet(ctx context.Context) ApiListTeamMembersApiV1OrgMembersGetRequest

	// ListTeamMembersApiV1OrgMembersGetExecute executes the request
	//  @return TeamMemberListResponse
	ListTeamMembersApiV1OrgMembersGetExecute(r ApiListTeamMembersApiV1OrgMembersGetRequest) (*TeamMemberListResponse, *http.Response, error)

	/*
	ListTeamMembersApiV1OrgMembersGet_0 List Team Members

	List all team members in the organization.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@return ApiListTeamMembersApiV1OrgMembersGet_0Request
	*/
	ListTeamMembersApiV1OrgMembersGet_4(ctx context.Context) ApiListTeamMembersApiV1OrgMembersGet_0Request

	// ListTeamMembersApiV1OrgMembersGet_4Execute executes the request
	//  @return TeamMemberListResponse
	ListTeamMembersApiV1OrgMembersGet_4Execute(r ApiListTeamMembersApiV1OrgMembersGet_0Request) (*TeamMemberListResponse, *http.Response, error)

	/*
	RemoveMemberApiV1OrgMembersMemberIdDelete Remove Member

	Remove a team member from the organization.

Cannot remove the owner.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param memberId
	@return ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest
	*/
	RemoveMemberApiV1OrgMembersMemberIdDelete(ctx context.Context, memberId string) ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest

	// RemoveMemberApiV1OrgMembersMemberIdDeleteExecute executes the request
	//  @return interface{}
	RemoveMemberApiV1OrgMembersMemberIdDeleteExecute(r ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest) (interface{}, *http.Response, error)

	/*
	RemoveMemberApiV1OrgMembersMemberIdDelete_0 Remove Member

	Remove a team member from the organization.

Cannot remove the owner.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param memberId
	@return ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request
	*/
	RemoveMemberApiV1OrgMembersMemberIdDelete_5(ctx context.Context, memberId string) ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request

	// RemoveMemberApiV1OrgMembersMemberIdDelete_5Execute executes the request
	//  @return interface{}
	RemoveMemberApiV1OrgMembersMemberIdDelete_5Execute(r ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request) (interface{}, *http.Response, error)

	/*
	RevokeInviteApiV1OrgMembersInvitesInviteIdDelete Revoke Invite

	Revoke a pending invitation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param inviteId
	@return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest
	*/
	RevokeInviteApiV1OrgMembersInvitesInviteIdDelete(ctx context.Context, inviteId string) ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest

	// RevokeInviteApiV1OrgMembersInvitesInviteIdDeleteExecute executes the request
	//  @return interface{}
	RevokeInviteApiV1OrgMembersInvitesInviteIdDeleteExecute(r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest) (interface{}, *http.Response, error)

	/*
	RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0 Revoke Invite

	Revoke a pending invitation.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param inviteId
	@return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request
	*/
	RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6(ctx context.Context, inviteId string) ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request

	// RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6Execute executes the request
	//  @return interface{}
	RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6Execute(r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request) (interface{}, *http.Response, error)

	/*
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch Update Member Role

	Update a team member's role.

Admins can change roles of members and viewers.
Only owners can change admin roles.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param memberId
	@return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest
	*/
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch(ctx context.Context, memberId string) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest

	// UpdateMemberRoleApiV1OrgMembersMemberIdRolePatchExecute executes the request
	//  @return interface{}
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatchExecute(r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest) (interface{}, *http.Response, error)

	/*
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0 Update Member Role

	Update a team member's role.

Admins can change roles of members and viewers.
Only owners can change admin roles.

	@param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
	@param memberId
	@return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request
	*/
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7(ctx context.Context, memberId string) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request

	// UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7Execute executes the request
	//  @return interface{}
	UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7Execute(r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request) (interface{}, *http.Response, error)
}

// TeamManagementAPIService TeamManagementAPI service
type TeamManagementAPIService service

type ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
	token *string
	userId *string
}

// Invitation token
func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest) Token(token string) ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest {
	r.token = &token
	return r
}

// User ID of the accepting user
func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest) UserId(userId string) ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest {
	r.userId = &userId
	return r
}

func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AcceptInviteApiV1OrgMembersAcceptInvitePostExecute(r)
}

/*
AcceptInviteApiV1OrgMembersAcceptInvitePost Accept Invite

Accept a team invitation.

This endpoint is called after the user authenticates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest
*/
func (a *TeamManagementAPIService) AcceptInviteApiV1OrgMembersAcceptInvitePost(ctx context.Context) ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest {
	return ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) AcceptInviteApiV1OrgMembersAcceptInvitePostExecute(r ApiAcceptInviteApiV1OrgMembersAcceptInvitePostRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.AcceptInviteApiV1OrgMembersAcceptInvitePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/accept-invite"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.token == nil {
		return localVarReturnValue, nil, reportError("token is required and must be specified")
	}
	if r.userId == nil {
		return localVarReturnValue, nil, reportError("userId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "token", r.token, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "user_id", r.userId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
	token *string
	userId *string
}

// Invitation token
func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request) Token(token string) ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request {
	r.token = &token
	return r
}

// User ID of the accepting user
func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request) UserId(userId string) ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request {
	r.userId = &userId
	return r
}

func (r ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.AcceptInviteApiV1OrgMembersAcceptInvitePost_1Execute(r)
}

/*
AcceptInviteApiV1OrgMembersAcceptInvitePost_0 Accept Invite

Accept a team invitation.

This endpoint is called after the user authenticates.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request
*/
func (a *TeamManagementAPIService) AcceptInviteApiV1OrgMembersAcceptInvitePost_1(ctx context.Context) ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request {
	return ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) AcceptInviteApiV1OrgMembersAcceptInvitePost_1Execute(r ApiAcceptInviteApiV1OrgMembersAcceptInvitePost_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.AcceptInviteApiV1OrgMembersAcceptInvitePost_1")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/accept-invite"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.token == nil {
		return localVarReturnValue, nil, reportError("token is required and must be specified")
	}
	if r.userId == nil {
		return localVarReturnValue, nil, reportError("userId is required and must be specified")
	}

	parameterAddToHeaderOrQuery(localVarQueryParams, "token", r.token, "form", "")
	parameterAddToHeaderOrQuery(localVarQueryParams, "user_id", r.userId, "form", "")
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiInviteMemberApiV1OrgMembersInvitePostRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
	inviteRequest *InviteRequest
}

func (r ApiInviteMemberApiV1OrgMembersInvitePostRequest) InviteRequest(inviteRequest InviteRequest) ApiInviteMemberApiV1OrgMembersInvitePostRequest {
	r.inviteRequest = &inviteRequest
	return r
}

func (r ApiInviteMemberApiV1OrgMembersInvitePostRequest) Execute() (*InviteResponse, *http.Response, error) {
	return r.ApiService.InviteMemberApiV1OrgMembersInvitePostExecute(r)
}

/*
InviteMemberApiV1OrgMembersInvitePost Invite Member

Invite a new member to the organization.

Sends an email invitation that expires in 7 days.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiInviteMemberApiV1OrgMembersInvitePostRequest
*/
func (a *TeamManagementAPIService) InviteMemberApiV1OrgMembersInvitePost(ctx context.Context) ApiInviteMemberApiV1OrgMembersInvitePostRequest {
	return ApiInviteMemberApiV1OrgMembersInvitePostRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return InviteResponse
func (a *TeamManagementAPIService) InviteMemberApiV1OrgMembersInvitePostExecute(r ApiInviteMemberApiV1OrgMembersInvitePostRequest) (*InviteResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *InviteResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.InviteMemberApiV1OrgMembersInvitePost")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invite"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.inviteRequest == nil {
		return localVarReturnValue, nil, reportError("inviteRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.inviteRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiInviteMemberApiV1OrgMembersInvitePost_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
	inviteRequest *InviteRequest
}

func (r ApiInviteMemberApiV1OrgMembersInvitePost_0Request) InviteRequest(inviteRequest InviteRequest) ApiInviteMemberApiV1OrgMembersInvitePost_0Request {
	r.inviteRequest = &inviteRequest
	return r
}

func (r ApiInviteMemberApiV1OrgMembersInvitePost_0Request) Execute() (*InviteResponse, *http.Response, error) {
	return r.ApiService.InviteMemberApiV1OrgMembersInvitePost_2Execute(r)
}

/*
InviteMemberApiV1OrgMembersInvitePost_0 Invite Member

Invite a new member to the organization.

Sends an email invitation that expires in 7 days.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiInviteMemberApiV1OrgMembersInvitePost_0Request
*/
func (a *TeamManagementAPIService) InviteMemberApiV1OrgMembersInvitePost_2(ctx context.Context) ApiInviteMemberApiV1OrgMembersInvitePost_0Request {
	return ApiInviteMemberApiV1OrgMembersInvitePost_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return InviteResponse
func (a *TeamManagementAPIService) InviteMemberApiV1OrgMembersInvitePost_2Execute(r ApiInviteMemberApiV1OrgMembersInvitePost_0Request) (*InviteResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPost
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *InviteResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.InviteMemberApiV1OrgMembersInvitePost_2")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invite"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.inviteRequest == nil {
		return localVarReturnValue, nil, reportError("inviteRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.inviteRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
}

func (r ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest) Execute() ([]PendingInvite, *http.Response, error) {
	return r.ApiService.ListPendingInvitesApiV1OrgMembersInvitesGetExecute(r)
}

/*
ListPendingInvitesApiV1OrgMembersInvitesGet List Pending Invites

List all pending invitations.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest
*/
func (a *TeamManagementAPIService) ListPendingInvitesApiV1OrgMembersInvitesGet(ctx context.Context) ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest {
	return ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []PendingInvite
func (a *TeamManagementAPIService) ListPendingInvitesApiV1OrgMembersInvitesGetExecute(r ApiListPendingInvitesApiV1OrgMembersInvitesGetRequest) ([]PendingInvite, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []PendingInvite
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.ListPendingInvitesApiV1OrgMembersInvitesGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invites"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
}

func (r ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request) Execute() ([]PendingInvite, *http.Response, error) {
	return r.ApiService.ListPendingInvitesApiV1OrgMembersInvitesGet_3Execute(r)
}

/*
ListPendingInvitesApiV1OrgMembersInvitesGet_0 List Pending Invites

List all pending invitations.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request
*/
func (a *TeamManagementAPIService) ListPendingInvitesApiV1OrgMembersInvitesGet_3(ctx context.Context) ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request {
	return ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return []PendingInvite
func (a *TeamManagementAPIService) ListPendingInvitesApiV1OrgMembersInvitesGet_3Execute(r ApiListPendingInvitesApiV1OrgMembersInvitesGet_0Request) ([]PendingInvite, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  []PendingInvite
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.ListPendingInvitesApiV1OrgMembersInvitesGet_3")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invites"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListTeamMembersApiV1OrgMembersGetRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
}

func (r ApiListTeamMembersApiV1OrgMembersGetRequest) Execute() (*TeamMemberListResponse, *http.Response, error) {
	return r.ApiService.ListTeamMembersApiV1OrgMembersGetExecute(r)
}

/*
ListTeamMembersApiV1OrgMembersGet List Team Members

List all team members in the organization.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListTeamMembersApiV1OrgMembersGetRequest
*/
func (a *TeamManagementAPIService) ListTeamMembersApiV1OrgMembersGet(ctx context.Context) ApiListTeamMembersApiV1OrgMembersGetRequest {
	return ApiListTeamMembersApiV1OrgMembersGetRequest{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TeamMemberListResponse
func (a *TeamManagementAPIService) ListTeamMembersApiV1OrgMembersGetExecute(r ApiListTeamMembersApiV1OrgMembersGetRequest) (*TeamMemberListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TeamMemberListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.ListTeamMembersApiV1OrgMembersGet")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiListTeamMembersApiV1OrgMembersGet_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
}

func (r ApiListTeamMembersApiV1OrgMembersGet_0Request) Execute() (*TeamMemberListResponse, *http.Response, error) {
	return r.ApiService.ListTeamMembersApiV1OrgMembersGet_4Execute(r)
}

/*
ListTeamMembersApiV1OrgMembersGet_0 List Team Members

List all team members in the organization.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @return ApiListTeamMembersApiV1OrgMembersGet_0Request
*/
func (a *TeamManagementAPIService) ListTeamMembersApiV1OrgMembersGet_4(ctx context.Context) ApiListTeamMembersApiV1OrgMembersGet_0Request {
	return ApiListTeamMembersApiV1OrgMembersGet_0Request{
		ApiService: a,
		ctx: ctx,
	}
}

// Execute executes the request
//  @return TeamMemberListResponse
func (a *TeamManagementAPIService) ListTeamMembersApiV1OrgMembersGet_4Execute(r ApiListTeamMembersApiV1OrgMembersGet_0Request) (*TeamMemberListResponse, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodGet
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  *TeamMemberListResponse
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.ListTeamMembersApiV1OrgMembersGet_4")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
	memberId string
}

func (r ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.RemoveMemberApiV1OrgMembersMemberIdDeleteExecute(r)
}

/*
RemoveMemberApiV1OrgMembersMemberIdDelete Remove Member

Remove a team member from the organization.

Cannot remove the owner.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param memberId
 @return ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest
*/
func (a *TeamManagementAPIService) RemoveMemberApiV1OrgMembersMemberIdDelete(ctx context.Context, memberId string) ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest {
	return ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		memberId: memberId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) RemoveMemberApiV1OrgMembersMemberIdDeleteExecute(r ApiRemoveMemberApiV1OrgMembersMemberIdDeleteRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.RemoveMemberApiV1OrgMembersMemberIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/{member_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"member_id"+"}", url.PathEscape(parameterValueToString(r.memberId, "memberId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
	memberId string
}

func (r ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.RemoveMemberApiV1OrgMembersMemberIdDelete_5Execute(r)
}

/*
RemoveMemberApiV1OrgMembersMemberIdDelete_0 Remove Member

Remove a team member from the organization.

Cannot remove the owner.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param memberId
 @return ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request
*/
func (a *TeamManagementAPIService) RemoveMemberApiV1OrgMembersMemberIdDelete_5(ctx context.Context, memberId string) ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request {
	return ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request{
		ApiService: a,
		ctx: ctx,
		memberId: memberId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) RemoveMemberApiV1OrgMembersMemberIdDelete_5Execute(r ApiRemoveMemberApiV1OrgMembersMemberIdDelete_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.RemoveMemberApiV1OrgMembersMemberIdDelete_5")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/{member_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"member_id"+"}", url.PathEscape(parameterValueToString(r.memberId, "memberId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
	inviteId string
}

func (r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.RevokeInviteApiV1OrgMembersInvitesInviteIdDeleteExecute(r)
}

/*
RevokeInviteApiV1OrgMembersInvitesInviteIdDelete Revoke Invite

Revoke a pending invitation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param inviteId
 @return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest
*/
func (a *TeamManagementAPIService) RevokeInviteApiV1OrgMembersInvitesInviteIdDelete(ctx context.Context, inviteId string) ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest {
	return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest{
		ApiService: a,
		ctx: ctx,
		inviteId: inviteId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) RevokeInviteApiV1OrgMembersInvitesInviteIdDeleteExecute(r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDeleteRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.RevokeInviteApiV1OrgMembersInvitesInviteIdDelete")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invites/{invite_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"invite_id"+"}", url.PathEscape(parameterValueToString(r.inviteId, "inviteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
	inviteId string
}

func (r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6Execute(r)
}

/*
RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0 Revoke Invite

Revoke a pending invitation.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param inviteId
 @return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request
*/
func (a *TeamManagementAPIService) RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6(ctx context.Context, inviteId string) ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request {
	return ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request{
		ApiService: a,
		ctx: ctx,
		inviteId: inviteId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6Execute(r ApiRevokeInviteApiV1OrgMembersInvitesInviteIdDelete_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodDelete
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.RevokeInviteApiV1OrgMembersInvitesInviteIdDelete_6")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/invites/{invite_id}"
	localVarPath = strings.Replace(localVarPath, "{"+"invite_id"+"}", url.PathEscape(parameterValueToString(r.inviteId, "inviteId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest struct {
	ctx context.Context
	ApiService TeamManagementAPI
	memberId string
	updateRoleRequest *UpdateRoleRequest
}

func (r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest) UpdateRoleRequest(updateRoleRequest UpdateRoleRequest) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest {
	r.updateRoleRequest = &updateRoleRequest
	return r
}

func (r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.UpdateMemberRoleApiV1OrgMembersMemberIdRolePatchExecute(r)
}

/*
UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch Update Member Role

Update a team member's role.

Admins can change roles of members and viewers.
Only owners can change admin roles.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param memberId
 @return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest
*/
func (a *TeamManagementAPIService) UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch(ctx context.Context, memberId string) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest {
	return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest{
		ApiService: a,
		ctx: ctx,
		memberId: memberId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) UpdateMemberRoleApiV1OrgMembersMemberIdRolePatchExecute(r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatchRequest) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/{member_id}/role"
	localVarPath = strings.Replace(localVarPath, "{"+"member_id"+"}", url.PathEscape(parameterValueToString(r.memberId, "memberId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateRoleRequest == nil {
		return localVarReturnValue, nil, reportError("updateRoleRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateRoleRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request struct {
	ctx context.Context
	ApiService TeamManagementAPI
	memberId string
	updateRoleRequest *UpdateRoleRequest
}

func (r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request) UpdateRoleRequest(updateRoleRequest UpdateRoleRequest) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request {
	r.updateRoleRequest = &updateRoleRequest
	return r
}

func (r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request) Execute() (interface{}, *http.Response, error) {
	return r.ApiService.UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7Execute(r)
}

/*
UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0 Update Member Role

Update a team member's role.

Admins can change roles of members and viewers.
Only owners can change admin roles.

 @param ctx context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 @param memberId
 @return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request
*/
func (a *TeamManagementAPIService) UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7(ctx context.Context, memberId string) ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request {
	return ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request{
		ApiService: a,
		ctx: ctx,
		memberId: memberId,
	}
}

// Execute executes the request
//  @return interface{}
func (a *TeamManagementAPIService) UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7Execute(r ApiUpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_0Request) (interface{}, *http.Response, error) {
	var (
		localVarHTTPMethod   = http.MethodPatch
		localVarPostBody     interface{}
		formFiles            []formFile
		localVarReturnValue  interface{}
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "TeamManagementAPIService.UpdateMemberRoleApiV1OrgMembersMemberIdRolePatch_7")
	if err != nil {
		return localVarReturnValue, nil, &GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/api/v1/org/members/{member_id}/role"
	localVarPath = strings.Replace(localVarPath, "{"+"member_id"+"}", url.PathEscape(parameterValueToString(r.memberId, "memberId")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := url.Values{}
	localVarFormParams := url.Values{}
	if r.updateRoleRequest == nil {
		return localVarReturnValue, nil, reportError("updateRoleRequest is required and must be specified")
	}

	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{"application/json"}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	// body params
	localVarPostBody = r.updateRoleRequest
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, formFiles)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := io.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = io.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		if localVarHTTPResponse.StatusCode == 422 {
			var v HTTPValidationError
			err = a.client.decode(&v, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
			if err != nil {
				newErr.error = err.Error()
				return localVarReturnValue, localVarHTTPResponse, newErr
			}
					newErr.error = formatErrorMessage(localVarHTTPResponse.Status, &v)
					newErr.model = v
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := &GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
