/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the EncodeWithEmbeddingsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EncodeWithEmbeddingsRequest{}

// EncodeWithEmbeddingsRequest Request to encode document with minimal signed embeddings.
type EncodeWithEmbeddingsRequest struct {
	// Unique document identifier
	DocumentId string `json:"document_id"`
	// Full document text to encode
	Text string `json:"text"`
	// Segmentation level: document (free tier, no segmentation), sentence, paragraph, section, word
	SegmentationLevel *string `json:"segmentation_level,omitempty"`
	// C2PA action type: c2pa.created (new content) or c2pa.edited (modified content)
	Action *string `json:"action,omitempty"`
	// Controls manifest detail level. Options: full, lightweight_uuid, hybrid. Availability depends on plan tier.
	ManifestMode *string `json:"manifest_mode,omitempty"`
	// Controls embedding placement strategy. Options: single_point, distributed, distributed_redundant. Availability depends on plan tier.
	EmbeddingStrategy *string `json:"embedding_strategy,omitempty"`
	DistributionTarget NullableString `json:"distribution_target,omitempty"`
	// Enable additional integrity binding. Availability depends on plan tier.
	AddDualBinding *bool `json:"add_dual_binding,omitempty"`
	// Opt-out of C2PA embedding. When true, only basic metadata is embedded.
	DisableC2pa *bool `json:"disable_c2pa,omitempty"`
	PreviousInstanceId NullableString `json:"previous_instance_id,omitempty"`
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	C2paManifestUrl NullableString `json:"c2pa_manifest_url,omitempty"`
	C2paManifestHash NullableString `json:"c2pa_manifest_hash,omitempty"`
	CustomAssertions []map[string]interface{} `json:"custom_assertions,omitempty"`
	TemplateId NullableString `json:"template_id,omitempty"`
	// Whether to validate custom assertions against registered schemas
	ValidateAssertions *bool `json:"validate_assertions,omitempty"`
	DigitalSourceType NullableString `json:"digital_source_type,omitempty"`
	License NullableLicenseInfo `json:"license,omitempty"`
	Rights NullableAppSchemasEmbeddingsRightsMetadata `json:"rights,omitempty"`
	// Embedding generation options
	EmbeddingOptions *EmbeddingOptions `json:"embedding_options,omitempty"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
}

type _EncodeWithEmbeddingsRequest EncodeWithEmbeddingsRequest

// NewEncodeWithEmbeddingsRequest instantiates a new EncodeWithEmbeddingsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEncodeWithEmbeddingsRequest(documentId string, text string) *EncodeWithEmbeddingsRequest {
	this := EncodeWithEmbeddingsRequest{}
	this.DocumentId = documentId
	this.Text = text
	var segmentationLevel string = "sentence"
	this.SegmentationLevel = &segmentationLevel
	var action string = "c2pa.created"
	this.Action = &action
	var manifestMode string = "full"
	this.ManifestMode = &manifestMode
	var embeddingStrategy string = "single_point"
	this.EmbeddingStrategy = &embeddingStrategy
	var addDualBinding bool = false
	this.AddDualBinding = &addDualBinding
	var disableC2pa bool = false
	this.DisableC2pa = &disableC2pa
	var validateAssertions bool = true
	this.ValidateAssertions = &validateAssertions
	return &this
}

// NewEncodeWithEmbeddingsRequestWithDefaults instantiates a new EncodeWithEmbeddingsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEncodeWithEmbeddingsRequestWithDefaults() *EncodeWithEmbeddingsRequest {
	this := EncodeWithEmbeddingsRequest{}
	var segmentationLevel string = "sentence"
	this.SegmentationLevel = &segmentationLevel
	var action string = "c2pa.created"
	this.Action = &action
	var manifestMode string = "full"
	this.ManifestMode = &manifestMode
	var embeddingStrategy string = "single_point"
	this.EmbeddingStrategy = &embeddingStrategy
	var addDualBinding bool = false
	this.AddDualBinding = &addDualBinding
	var disableC2pa bool = false
	this.DisableC2pa = &disableC2pa
	var validateAssertions bool = true
	this.ValidateAssertions = &validateAssertions
	return &this
}

// GetDocumentId returns the DocumentId field value
func (o *EncodeWithEmbeddingsRequest) GetDocumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *EncodeWithEmbeddingsRequest) SetDocumentId(v string) {
	o.DocumentId = v
}

// GetText returns the Text field value
func (o *EncodeWithEmbeddingsRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *EncodeWithEmbeddingsRequest) SetText(v string) {
	o.Text = v
}

// GetSegmentationLevel returns the SegmentationLevel field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetSegmentationLevel() string {
	if o == nil || IsNil(o.SegmentationLevel) {
		var ret string
		return ret
	}
	return *o.SegmentationLevel
}

// GetSegmentationLevelOk returns a tuple with the SegmentationLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetSegmentationLevelOk() (*string, bool) {
	if o == nil || IsNil(o.SegmentationLevel) {
		return nil, false
	}
	return o.SegmentationLevel, true
}

// HasSegmentationLevel returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasSegmentationLevel() bool {
	if o != nil && !IsNil(o.SegmentationLevel) {
		return true
	}

	return false
}

// SetSegmentationLevel gets a reference to the given string and assigns it to the SegmentationLevel field.
func (o *EncodeWithEmbeddingsRequest) SetSegmentationLevel(v string) {
	o.SegmentationLevel = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetAction() string {
	if o == nil || IsNil(o.Action) {
		var ret string
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetActionOk() (*string, bool) {
	if o == nil || IsNil(o.Action) {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasAction() bool {
	if o != nil && !IsNil(o.Action) {
		return true
	}

	return false
}

// SetAction gets a reference to the given string and assigns it to the Action field.
func (o *EncodeWithEmbeddingsRequest) SetAction(v string) {
	o.Action = &v
}

// GetManifestMode returns the ManifestMode field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetManifestMode() string {
	if o == nil || IsNil(o.ManifestMode) {
		var ret string
		return ret
	}
	return *o.ManifestMode
}

// GetManifestModeOk returns a tuple with the ManifestMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetManifestModeOk() (*string, bool) {
	if o == nil || IsNil(o.ManifestMode) {
		return nil, false
	}
	return o.ManifestMode, true
}

// HasManifestMode returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasManifestMode() bool {
	if o != nil && !IsNil(o.ManifestMode) {
		return true
	}

	return false
}

// SetManifestMode gets a reference to the given string and assigns it to the ManifestMode field.
func (o *EncodeWithEmbeddingsRequest) SetManifestMode(v string) {
	o.ManifestMode = &v
}

// GetEmbeddingStrategy returns the EmbeddingStrategy field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetEmbeddingStrategy() string {
	if o == nil || IsNil(o.EmbeddingStrategy) {
		var ret string
		return ret
	}
	return *o.EmbeddingStrategy
}

// GetEmbeddingStrategyOk returns a tuple with the EmbeddingStrategy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetEmbeddingStrategyOk() (*string, bool) {
	if o == nil || IsNil(o.EmbeddingStrategy) {
		return nil, false
	}
	return o.EmbeddingStrategy, true
}

// HasEmbeddingStrategy returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasEmbeddingStrategy() bool {
	if o != nil && !IsNil(o.EmbeddingStrategy) {
		return true
	}

	return false
}

// SetEmbeddingStrategy gets a reference to the given string and assigns it to the EmbeddingStrategy field.
func (o *EncodeWithEmbeddingsRequest) SetEmbeddingStrategy(v string) {
	o.EmbeddingStrategy = &v
}

// GetDistributionTarget returns the DistributionTarget field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetDistributionTarget() string {
	if o == nil || IsNil(o.DistributionTarget.Get()) {
		var ret string
		return ret
	}
	return *o.DistributionTarget.Get()
}

// GetDistributionTargetOk returns a tuple with the DistributionTarget field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetDistributionTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DistributionTarget.Get(), o.DistributionTarget.IsSet()
}

// HasDistributionTarget returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasDistributionTarget() bool {
	if o != nil && o.DistributionTarget.IsSet() {
		return true
	}

	return false
}

// SetDistributionTarget gets a reference to the given NullableString and assigns it to the DistributionTarget field.
func (o *EncodeWithEmbeddingsRequest) SetDistributionTarget(v string) {
	o.DistributionTarget.Set(&v)
}
// SetDistributionTargetNil sets the value for DistributionTarget to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetDistributionTargetNil() {
	o.DistributionTarget.Set(nil)
}

// UnsetDistributionTarget ensures that no value is present for DistributionTarget, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetDistributionTarget() {
	o.DistributionTarget.Unset()
}

// GetAddDualBinding returns the AddDualBinding field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetAddDualBinding() bool {
	if o == nil || IsNil(o.AddDualBinding) {
		var ret bool
		return ret
	}
	return *o.AddDualBinding
}

// GetAddDualBindingOk returns a tuple with the AddDualBinding field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetAddDualBindingOk() (*bool, bool) {
	if o == nil || IsNil(o.AddDualBinding) {
		return nil, false
	}
	return o.AddDualBinding, true
}

// HasAddDualBinding returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasAddDualBinding() bool {
	if o != nil && !IsNil(o.AddDualBinding) {
		return true
	}

	return false
}

// SetAddDualBinding gets a reference to the given bool and assigns it to the AddDualBinding field.
func (o *EncodeWithEmbeddingsRequest) SetAddDualBinding(v bool) {
	o.AddDualBinding = &v
}

// GetDisableC2pa returns the DisableC2pa field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetDisableC2pa() bool {
	if o == nil || IsNil(o.DisableC2pa) {
		var ret bool
		return ret
	}
	return *o.DisableC2pa
}

// GetDisableC2paOk returns a tuple with the DisableC2pa field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetDisableC2paOk() (*bool, bool) {
	if o == nil || IsNil(o.DisableC2pa) {
		return nil, false
	}
	return o.DisableC2pa, true
}

// HasDisableC2pa returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasDisableC2pa() bool {
	if o != nil && !IsNil(o.DisableC2pa) {
		return true
	}

	return false
}

// SetDisableC2pa gets a reference to the given bool and assigns it to the DisableC2pa field.
func (o *EncodeWithEmbeddingsRequest) SetDisableC2pa(v bool) {
	o.DisableC2pa = &v
}

// GetPreviousInstanceId returns the PreviousInstanceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetPreviousInstanceId() string {
	if o == nil || IsNil(o.PreviousInstanceId.Get()) {
		var ret string
		return ret
	}
	return *o.PreviousInstanceId.Get()
}

// GetPreviousInstanceIdOk returns a tuple with the PreviousInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetPreviousInstanceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PreviousInstanceId.Get(), o.PreviousInstanceId.IsSet()
}

// HasPreviousInstanceId returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasPreviousInstanceId() bool {
	if o != nil && o.PreviousInstanceId.IsSet() {
		return true
	}

	return false
}

// SetPreviousInstanceId gets a reference to the given NullableString and assigns it to the PreviousInstanceId field.
func (o *EncodeWithEmbeddingsRequest) SetPreviousInstanceId(v string) {
	o.PreviousInstanceId.Set(&v)
}
// SetPreviousInstanceIdNil sets the value for PreviousInstanceId to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetPreviousInstanceIdNil() {
	o.PreviousInstanceId.Set(nil)
}

// UnsetPreviousInstanceId ensures that no value is present for PreviousInstanceId, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetPreviousInstanceId() {
	o.PreviousInstanceId.Unset()
}

// GetMetadata returns the Metadata field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetMetadata() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetMetadataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Metadata) {
		return map[string]interface{}{}, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given map[string]interface{} and assigns it to the Metadata field.
func (o *EncodeWithEmbeddingsRequest) SetMetadata(v map[string]interface{}) {
	o.Metadata = v
}

// GetC2paManifestUrl returns the C2paManifestUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetC2paManifestUrl() string {
	if o == nil || IsNil(o.C2paManifestUrl.Get()) {
		var ret string
		return ret
	}
	return *o.C2paManifestUrl.Get()
}

// GetC2paManifestUrlOk returns a tuple with the C2paManifestUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetC2paManifestUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.C2paManifestUrl.Get(), o.C2paManifestUrl.IsSet()
}

// HasC2paManifestUrl returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasC2paManifestUrl() bool {
	if o != nil && o.C2paManifestUrl.IsSet() {
		return true
	}

	return false
}

// SetC2paManifestUrl gets a reference to the given NullableString and assigns it to the C2paManifestUrl field.
func (o *EncodeWithEmbeddingsRequest) SetC2paManifestUrl(v string) {
	o.C2paManifestUrl.Set(&v)
}
// SetC2paManifestUrlNil sets the value for C2paManifestUrl to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetC2paManifestUrlNil() {
	o.C2paManifestUrl.Set(nil)
}

// UnsetC2paManifestUrl ensures that no value is present for C2paManifestUrl, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetC2paManifestUrl() {
	o.C2paManifestUrl.Unset()
}

// GetC2paManifestHash returns the C2paManifestHash field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetC2paManifestHash() string {
	if o == nil || IsNil(o.C2paManifestHash.Get()) {
		var ret string
		return ret
	}
	return *o.C2paManifestHash.Get()
}

// GetC2paManifestHashOk returns a tuple with the C2paManifestHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetC2paManifestHashOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.C2paManifestHash.Get(), o.C2paManifestHash.IsSet()
}

// HasC2paManifestHash returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasC2paManifestHash() bool {
	if o != nil && o.C2paManifestHash.IsSet() {
		return true
	}

	return false
}

// SetC2paManifestHash gets a reference to the given NullableString and assigns it to the C2paManifestHash field.
func (o *EncodeWithEmbeddingsRequest) SetC2paManifestHash(v string) {
	o.C2paManifestHash.Set(&v)
}
// SetC2paManifestHashNil sets the value for C2paManifestHash to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetC2paManifestHashNil() {
	o.C2paManifestHash.Set(nil)
}

// UnsetC2paManifestHash ensures that no value is present for C2paManifestHash, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetC2paManifestHash() {
	o.C2paManifestHash.Unset()
}

// GetCustomAssertions returns the CustomAssertions field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetCustomAssertions() []map[string]interface{} {
	if o == nil {
		var ret []map[string]interface{}
		return ret
	}
	return o.CustomAssertions
}

// GetCustomAssertionsOk returns a tuple with the CustomAssertions field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetCustomAssertionsOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomAssertions) {
		return nil, false
	}
	return o.CustomAssertions, true
}

// HasCustomAssertions returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasCustomAssertions() bool {
	if o != nil && !IsNil(o.CustomAssertions) {
		return true
	}

	return false
}

// SetCustomAssertions gets a reference to the given []map[string]interface{} and assigns it to the CustomAssertions field.
func (o *EncodeWithEmbeddingsRequest) SetCustomAssertions(v []map[string]interface{}) {
	o.CustomAssertions = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId.Get()) {
		var ret string
		return ret
	}
	return *o.TemplateId.Get()
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TemplateId.Get(), o.TemplateId.IsSet()
}

// HasTemplateId returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasTemplateId() bool {
	if o != nil && o.TemplateId.IsSet() {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given NullableString and assigns it to the TemplateId field.
func (o *EncodeWithEmbeddingsRequest) SetTemplateId(v string) {
	o.TemplateId.Set(&v)
}
// SetTemplateIdNil sets the value for TemplateId to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetTemplateIdNil() {
	o.TemplateId.Set(nil)
}

// UnsetTemplateId ensures that no value is present for TemplateId, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetTemplateId() {
	o.TemplateId.Unset()
}

// GetValidateAssertions returns the ValidateAssertions field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetValidateAssertions() bool {
	if o == nil || IsNil(o.ValidateAssertions) {
		var ret bool
		return ret
	}
	return *o.ValidateAssertions
}

// GetValidateAssertionsOk returns a tuple with the ValidateAssertions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetValidateAssertionsOk() (*bool, bool) {
	if o == nil || IsNil(o.ValidateAssertions) {
		return nil, false
	}
	return o.ValidateAssertions, true
}

// HasValidateAssertions returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasValidateAssertions() bool {
	if o != nil && !IsNil(o.ValidateAssertions) {
		return true
	}

	return false
}

// SetValidateAssertions gets a reference to the given bool and assigns it to the ValidateAssertions field.
func (o *EncodeWithEmbeddingsRequest) SetValidateAssertions(v bool) {
	o.ValidateAssertions = &v
}

// GetDigitalSourceType returns the DigitalSourceType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetDigitalSourceType() string {
	if o == nil || IsNil(o.DigitalSourceType.Get()) {
		var ret string
		return ret
	}
	return *o.DigitalSourceType.Get()
}

// GetDigitalSourceTypeOk returns a tuple with the DigitalSourceType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetDigitalSourceTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DigitalSourceType.Get(), o.DigitalSourceType.IsSet()
}

// HasDigitalSourceType returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasDigitalSourceType() bool {
	if o != nil && o.DigitalSourceType.IsSet() {
		return true
	}

	return false
}

// SetDigitalSourceType gets a reference to the given NullableString and assigns it to the DigitalSourceType field.
func (o *EncodeWithEmbeddingsRequest) SetDigitalSourceType(v string) {
	o.DigitalSourceType.Set(&v)
}
// SetDigitalSourceTypeNil sets the value for DigitalSourceType to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetDigitalSourceTypeNil() {
	o.DigitalSourceType.Set(nil)
}

// UnsetDigitalSourceType ensures that no value is present for DigitalSourceType, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetDigitalSourceType() {
	o.DigitalSourceType.Unset()
}

// GetLicense returns the License field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetLicense() LicenseInfo {
	if o == nil || IsNil(o.License.Get()) {
		var ret LicenseInfo
		return ret
	}
	return *o.License.Get()
}

// GetLicenseOk returns a tuple with the License field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetLicenseOk() (*LicenseInfo, bool) {
	if o == nil {
		return nil, false
	}
	return o.License.Get(), o.License.IsSet()
}

// HasLicense returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasLicense() bool {
	if o != nil && o.License.IsSet() {
		return true
	}

	return false
}

// SetLicense gets a reference to the given NullableLicenseInfo and assigns it to the License field.
func (o *EncodeWithEmbeddingsRequest) SetLicense(v LicenseInfo) {
	o.License.Set(&v)
}
// SetLicenseNil sets the value for License to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetLicenseNil() {
	o.License.Set(nil)
}

// UnsetLicense ensures that no value is present for License, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetLicense() {
	o.License.Unset()
}

// GetRights returns the Rights field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetRights() AppSchemasEmbeddingsRightsMetadata {
	if o == nil || IsNil(o.Rights.Get()) {
		var ret AppSchemasEmbeddingsRightsMetadata
		return ret
	}
	return *o.Rights.Get()
}

// GetRightsOk returns a tuple with the Rights field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetRightsOk() (*AppSchemasEmbeddingsRightsMetadata, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rights.Get(), o.Rights.IsSet()
}

// HasRights returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasRights() bool {
	if o != nil && o.Rights.IsSet() {
		return true
	}

	return false
}

// SetRights gets a reference to the given NullableAppSchemasEmbeddingsRightsMetadata and assigns it to the Rights field.
func (o *EncodeWithEmbeddingsRequest) SetRights(v AppSchemasEmbeddingsRightsMetadata) {
	o.Rights.Set(&v)
}
// SetRightsNil sets the value for Rights to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetRightsNil() {
	o.Rights.Set(nil)
}

// UnsetRights ensures that no value is present for Rights, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetRights() {
	o.Rights.Unset()
}

// GetEmbeddingOptions returns the EmbeddingOptions field value if set, zero value otherwise.
func (o *EncodeWithEmbeddingsRequest) GetEmbeddingOptions() EmbeddingOptions {
	if o == nil || IsNil(o.EmbeddingOptions) {
		var ret EmbeddingOptions
		return ret
	}
	return *o.EmbeddingOptions
}

// GetEmbeddingOptionsOk returns a tuple with the EmbeddingOptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EncodeWithEmbeddingsRequest) GetEmbeddingOptionsOk() (*EmbeddingOptions, bool) {
	if o == nil || IsNil(o.EmbeddingOptions) {
		return nil, false
	}
	return o.EmbeddingOptions, true
}

// HasEmbeddingOptions returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasEmbeddingOptions() bool {
	if o != nil && !IsNil(o.EmbeddingOptions) {
		return true
	}

	return false
}

// SetEmbeddingOptions gets a reference to the given EmbeddingOptions and assigns it to the EmbeddingOptions field.
func (o *EncodeWithEmbeddingsRequest) SetEmbeddingOptions(v EmbeddingOptions) {
	o.EmbeddingOptions = &v
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EncodeWithEmbeddingsRequest) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EncodeWithEmbeddingsRequest) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *EncodeWithEmbeddingsRequest) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *EncodeWithEmbeddingsRequest) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *EncodeWithEmbeddingsRequest) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *EncodeWithEmbeddingsRequest) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

func (o EncodeWithEmbeddingsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EncodeWithEmbeddingsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["document_id"] = o.DocumentId
	toSerialize["text"] = o.Text
	if !IsNil(o.SegmentationLevel) {
		toSerialize["segmentation_level"] = o.SegmentationLevel
	}
	if !IsNil(o.Action) {
		toSerialize["action"] = o.Action
	}
	if !IsNil(o.ManifestMode) {
		toSerialize["manifest_mode"] = o.ManifestMode
	}
	if !IsNil(o.EmbeddingStrategy) {
		toSerialize["embedding_strategy"] = o.EmbeddingStrategy
	}
	if o.DistributionTarget.IsSet() {
		toSerialize["distribution_target"] = o.DistributionTarget.Get()
	}
	if !IsNil(o.AddDualBinding) {
		toSerialize["add_dual_binding"] = o.AddDualBinding
	}
	if !IsNil(o.DisableC2pa) {
		toSerialize["disable_c2pa"] = o.DisableC2pa
	}
	if o.PreviousInstanceId.IsSet() {
		toSerialize["previous_instance_id"] = o.PreviousInstanceId.Get()
	}
	if o.Metadata != nil {
		toSerialize["metadata"] = o.Metadata
	}
	if o.C2paManifestUrl.IsSet() {
		toSerialize["c2pa_manifest_url"] = o.C2paManifestUrl.Get()
	}
	if o.C2paManifestHash.IsSet() {
		toSerialize["c2pa_manifest_hash"] = o.C2paManifestHash.Get()
	}
	if o.CustomAssertions != nil {
		toSerialize["custom_assertions"] = o.CustomAssertions
	}
	if o.TemplateId.IsSet() {
		toSerialize["template_id"] = o.TemplateId.Get()
	}
	if !IsNil(o.ValidateAssertions) {
		toSerialize["validate_assertions"] = o.ValidateAssertions
	}
	if o.DigitalSourceType.IsSet() {
		toSerialize["digital_source_type"] = o.DigitalSourceType.Get()
	}
	if o.License.IsSet() {
		toSerialize["license"] = o.License.Get()
	}
	if o.Rights.IsSet() {
		toSerialize["rights"] = o.Rights.Get()
	}
	if !IsNil(o.EmbeddingOptions) {
		toSerialize["embedding_options"] = o.EmbeddingOptions
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	return toSerialize, nil
}

func (o *EncodeWithEmbeddingsRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"document_id",
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEncodeWithEmbeddingsRequest := _EncodeWithEmbeddingsRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEncodeWithEmbeddingsRequest)

	if err != nil {
		return err
	}

	*o = EncodeWithEmbeddingsRequest(varEncodeWithEmbeddingsRequest)

	return err
}

type NullableEncodeWithEmbeddingsRequest struct {
	value *EncodeWithEmbeddingsRequest
	isSet bool
}

func (v NullableEncodeWithEmbeddingsRequest) Get() *EncodeWithEmbeddingsRequest {
	return v.value
}

func (v *NullableEncodeWithEmbeddingsRequest) Set(val *EncodeWithEmbeddingsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableEncodeWithEmbeddingsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableEncodeWithEmbeddingsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncodeWithEmbeddingsRequest(val *EncodeWithEmbeddingsRequest) *NullableEncodeWithEmbeddingsRequest {
	return &NullableEncodeWithEmbeddingsRequest{value: val, isSet: true}
}

func (v NullableEncodeWithEmbeddingsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncodeWithEmbeddingsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


