/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the C2PASchemaCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &C2PASchemaCreate{}

// C2PASchemaCreate Request schema for creating a C2PA assertion schema.
type C2PASchemaCreate struct {
	// Human-readable name for the schema
	Name string `json:"name"`
	// Full assertion label (e.g., 'com.acme.legal.v1')
	Label string `json:"label"`
	// Schema version (e.g., 'v1', '1.0.0')
	Version *string `json:"version,omitempty"`
	// JSON Schema for validation
	JsonSchema map[string]interface{} `json:"json_schema"`
	Description NullableString `json:"description,omitempty"`
	// Whether schema is publicly accessible
	IsPublic *bool `json:"is_public,omitempty"`
}

type _C2PASchemaCreate C2PASchemaCreate

// NewC2PASchemaCreate instantiates a new C2PASchemaCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewC2PASchemaCreate(name string, label string, jsonSchema map[string]interface{}) *C2PASchemaCreate {
	this := C2PASchemaCreate{}
	this.Name = name
	this.Label = label
	var version string = "1.0"
	this.Version = &version
	this.JsonSchema = jsonSchema
	var isPublic bool = false
	this.IsPublic = &isPublic
	return &this
}

// NewC2PASchemaCreateWithDefaults instantiates a new C2PASchemaCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewC2PASchemaCreateWithDefaults() *C2PASchemaCreate {
	this := C2PASchemaCreate{}
	var version string = "1.0"
	this.Version = &version
	var isPublic bool = false
	this.IsPublic = &isPublic
	return &this
}

// GetName returns the Name field value
func (o *C2PASchemaCreate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *C2PASchemaCreate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *C2PASchemaCreate) SetName(v string) {
	o.Name = v
}

// GetLabel returns the Label field value
func (o *C2PASchemaCreate) GetLabel() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Label
}

// GetLabelOk returns a tuple with the Label field value
// and a boolean to check if the value has been set.
func (o *C2PASchemaCreate) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Label, true
}

// SetLabel sets field value
func (o *C2PASchemaCreate) SetLabel(v string) {
	o.Label = v
}

// GetVersion returns the Version field value if set, zero value otherwise.
func (o *C2PASchemaCreate) GetVersion() string {
	if o == nil || IsNil(o.Version) {
		var ret string
		return ret
	}
	return *o.Version
}

// GetVersionOk returns a tuple with the Version field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C2PASchemaCreate) GetVersionOk() (*string, bool) {
	if o == nil || IsNil(o.Version) {
		return nil, false
	}
	return o.Version, true
}

// HasVersion returns a boolean if a field has been set.
func (o *C2PASchemaCreate) HasVersion() bool {
	if o != nil && !IsNil(o.Version) {
		return true
	}

	return false
}

// SetVersion gets a reference to the given string and assigns it to the Version field.
func (o *C2PASchemaCreate) SetVersion(v string) {
	o.Version = &v
}

// GetJsonSchema returns the JsonSchema field value
func (o *C2PASchemaCreate) GetJsonSchema() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.JsonSchema
}

// GetJsonSchemaOk returns a tuple with the JsonSchema field value
// and a boolean to check if the value has been set.
func (o *C2PASchemaCreate) GetJsonSchemaOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.JsonSchema, true
}

// SetJsonSchema sets field value
func (o *C2PASchemaCreate) SetJsonSchema(v map[string]interface{}) {
	o.JsonSchema = v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *C2PASchemaCreate) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *C2PASchemaCreate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *C2PASchemaCreate) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *C2PASchemaCreate) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *C2PASchemaCreate) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *C2PASchemaCreate) UnsetDescription() {
	o.Description.Unset()
}

// GetIsPublic returns the IsPublic field value if set, zero value otherwise.
func (o *C2PASchemaCreate) GetIsPublic() bool {
	if o == nil || IsNil(o.IsPublic) {
		var ret bool
		return ret
	}
	return *o.IsPublic
}

// GetIsPublicOk returns a tuple with the IsPublic field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *C2PASchemaCreate) GetIsPublicOk() (*bool, bool) {
	if o == nil || IsNil(o.IsPublic) {
		return nil, false
	}
	return o.IsPublic, true
}

// HasIsPublic returns a boolean if a field has been set.
func (o *C2PASchemaCreate) HasIsPublic() bool {
	if o != nil && !IsNil(o.IsPublic) {
		return true
	}

	return false
}

// SetIsPublic gets a reference to the given bool and assigns it to the IsPublic field.
func (o *C2PASchemaCreate) SetIsPublic(v bool) {
	o.IsPublic = &v
}

func (o C2PASchemaCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o C2PASchemaCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["label"] = o.Label
	if !IsNil(o.Version) {
		toSerialize["version"] = o.Version
	}
	toSerialize["json_schema"] = o.JsonSchema
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.IsPublic) {
		toSerialize["is_public"] = o.IsPublic
	}
	return toSerialize, nil
}

func (o *C2PASchemaCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"label",
		"json_schema",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varC2PASchemaCreate := _C2PASchemaCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varC2PASchemaCreate)

	if err != nil {
		return err
	}

	*o = C2PASchemaCreate(varC2PASchemaCreate)

	return err
}

type NullableC2PASchemaCreate struct {
	value *C2PASchemaCreate
	isSet bool
}

func (v NullableC2PASchemaCreate) Get() *C2PASchemaCreate {
	return v.value
}

func (v *NullableC2PASchemaCreate) Set(val *C2PASchemaCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableC2PASchemaCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableC2PASchemaCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableC2PASchemaCreate(val *C2PASchemaCreate) *NullableC2PASchemaCreate {
	return &NullableC2PASchemaCreate{value: val, isSet: true}
}

func (v NullableC2PASchemaCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableC2PASchemaCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


