/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KeyCreateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KeyCreateResponse{}

// KeyCreateResponse Response after creating a key (includes full key - only shown once).
type KeyCreateResponse struct {
	Success *bool `json:"success,omitempty"`
	Data map[string]interface{} `json:"data"`
	Warning *string `json:"warning,omitempty"`
}

type _KeyCreateResponse KeyCreateResponse

// NewKeyCreateResponse instantiates a new KeyCreateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKeyCreateResponse(data map[string]interface{}) *KeyCreateResponse {
	this := KeyCreateResponse{}
	var success bool = true
	this.Success = &success
	this.Data = data
	var warning string = "Store this key securely. It will not be shown again."
	this.Warning = &warning
	return &this
}

// NewKeyCreateResponseWithDefaults instantiates a new KeyCreateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKeyCreateResponseWithDefaults() *KeyCreateResponse {
	this := KeyCreateResponse{}
	var success bool = true
	this.Success = &success
	var warning string = "Store this key securely. It will not be shown again."
	this.Warning = &warning
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *KeyCreateResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyCreateResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *KeyCreateResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *KeyCreateResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value
func (o *KeyCreateResponse) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *KeyCreateResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *KeyCreateResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

// GetWarning returns the Warning field value if set, zero value otherwise.
func (o *KeyCreateResponse) GetWarning() string {
	if o == nil || IsNil(o.Warning) {
		var ret string
		return ret
	}
	return *o.Warning
}

// GetWarningOk returns a tuple with the Warning field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KeyCreateResponse) GetWarningOk() (*string, bool) {
	if o == nil || IsNil(o.Warning) {
		return nil, false
	}
	return o.Warning, true
}

// HasWarning returns a boolean if a field has been set.
func (o *KeyCreateResponse) HasWarning() bool {
	if o != nil && !IsNil(o.Warning) {
		return true
	}

	return false
}

// SetWarning gets a reference to the given string and assigns it to the Warning field.
func (o *KeyCreateResponse) SetWarning(v string) {
	o.Warning = &v
}

func (o KeyCreateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KeyCreateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	toSerialize["data"] = o.Data
	if !IsNil(o.Warning) {
		toSerialize["warning"] = o.Warning
	}
	return toSerialize, nil
}

func (o *KeyCreateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKeyCreateResponse := _KeyCreateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKeyCreateResponse)

	if err != nil {
		return err
	}

	*o = KeyCreateResponse(varKeyCreateResponse)

	return err
}

type NullableKeyCreateResponse struct {
	value *KeyCreateResponse
	isSet bool
}

func (v NullableKeyCreateResponse) Get() *KeyCreateResponse {
	return v.value
}

func (v *NullableKeyCreateResponse) Set(val *KeyCreateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKeyCreateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKeyCreateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKeyCreateResponse(val *KeyCreateResponse) *NullableKeyCreateResponse {
	return &NullableKeyCreateResponse{value: val, isSet: true}
}

func (v NullableKeyCreateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKeyCreateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


