/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.0-preview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BatchResponseEnvelope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BatchResponseEnvelope{}

// BatchResponseEnvelope Envelope returned by batch endpoints.
type BatchResponseEnvelope struct {
	// Indicates whether the batch request succeeded
	Success bool `json:"success"`
	// Batch request identifier
	BatchId string `json:"batch_id"`
	Data NullableBatchResponseData `json:"data,omitempty"`
	Error NullableErrorDetail `json:"error,omitempty"`
	// Request correlation identifier for tracing
	CorrelationId string `json:"correlation_id"`
}

type _BatchResponseEnvelope BatchResponseEnvelope

// NewBatchResponseEnvelope instantiates a new BatchResponseEnvelope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBatchResponseEnvelope(success bool, batchId string, correlationId string) *BatchResponseEnvelope {
	this := BatchResponseEnvelope{}
	this.Success = success
	this.BatchId = batchId
	this.CorrelationId = correlationId
	return &this
}

// NewBatchResponseEnvelopeWithDefaults instantiates a new BatchResponseEnvelope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBatchResponseEnvelopeWithDefaults() *BatchResponseEnvelope {
	this := BatchResponseEnvelope{}
	return &this
}

// GetSuccess returns the Success field value
func (o *BatchResponseEnvelope) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *BatchResponseEnvelope) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *BatchResponseEnvelope) SetSuccess(v bool) {
	o.Success = v
}

// GetBatchId returns the BatchId field value
func (o *BatchResponseEnvelope) GetBatchId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.BatchId
}

// GetBatchIdOk returns a tuple with the BatchId field value
// and a boolean to check if the value has been set.
func (o *BatchResponseEnvelope) GetBatchIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.BatchId, true
}

// SetBatchId sets field value
func (o *BatchResponseEnvelope) SetBatchId(v string) {
	o.BatchId = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchResponseEnvelope) GetData() BatchResponseData {
	if o == nil || IsNil(o.Data.Get()) {
		var ret BatchResponseData
		return ret
	}
	return *o.Data.Get()
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchResponseEnvelope) GetDataOk() (*BatchResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data.Get(), o.Data.IsSet()
}

// HasData returns a boolean if a field has been set.
func (o *BatchResponseEnvelope) HasData() bool {
	if o != nil && o.Data.IsSet() {
		return true
	}

	return false
}

// SetData gets a reference to the given NullableBatchResponseData and assigns it to the Data field.
func (o *BatchResponseEnvelope) SetData(v BatchResponseData) {
	o.Data.Set(&v)
}
// SetDataNil sets the value for Data to be an explicit nil
func (o *BatchResponseEnvelope) SetDataNil() {
	o.Data.Set(nil)
}

// UnsetData ensures that no value is present for Data, not even an explicit nil
func (o *BatchResponseEnvelope) UnsetData() {
	o.Data.Unset()
}

// GetError returns the Error field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BatchResponseEnvelope) GetError() ErrorDetail {
	if o == nil || IsNil(o.Error.Get()) {
		var ret ErrorDetail
		return ret
	}
	return *o.Error.Get()
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BatchResponseEnvelope) GetErrorOk() (*ErrorDetail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Error.Get(), o.Error.IsSet()
}

// HasError returns a boolean if a field has been set.
func (o *BatchResponseEnvelope) HasError() bool {
	if o != nil && o.Error.IsSet() {
		return true
	}

	return false
}

// SetError gets a reference to the given NullableErrorDetail and assigns it to the Error field.
func (o *BatchResponseEnvelope) SetError(v ErrorDetail) {
	o.Error.Set(&v)
}
// SetErrorNil sets the value for Error to be an explicit nil
func (o *BatchResponseEnvelope) SetErrorNil() {
	o.Error.Set(nil)
}

// UnsetError ensures that no value is present for Error, not even an explicit nil
func (o *BatchResponseEnvelope) UnsetError() {
	o.Error.Unset()
}

// GetCorrelationId returns the CorrelationId field value
func (o *BatchResponseEnvelope) GetCorrelationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CorrelationId
}

// GetCorrelationIdOk returns a tuple with the CorrelationId field value
// and a boolean to check if the value has been set.
func (o *BatchResponseEnvelope) GetCorrelationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CorrelationId, true
}

// SetCorrelationId sets field value
func (o *BatchResponseEnvelope) SetCorrelationId(v string) {
	o.CorrelationId = v
}

func (o BatchResponseEnvelope) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BatchResponseEnvelope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["batch_id"] = o.BatchId
	if o.Data.IsSet() {
		toSerialize["data"] = o.Data.Get()
	}
	if o.Error.IsSet() {
		toSerialize["error"] = o.Error.Get()
	}
	toSerialize["correlation_id"] = o.CorrelationId
	return toSerialize, nil
}

func (o *BatchResponseEnvelope) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"batch_id",
		"correlation_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBatchResponseEnvelope := _BatchResponseEnvelope{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBatchResponseEnvelope)

	if err != nil {
		return err
	}

	*o = BatchResponseEnvelope(varBatchResponseEnvelope)

	return err
}

type NullableBatchResponseEnvelope struct {
	value *BatchResponseEnvelope
	isSet bool
}

func (v NullableBatchResponseEnvelope) Get() *BatchResponseEnvelope {
	return v.value
}

func (v *NullableBatchResponseEnvelope) Set(val *BatchResponseEnvelope) {
	v.value = val
	v.isSet = true
}

func (v NullableBatchResponseEnvelope) IsSet() bool {
	return v.isSet
}

func (v *NullableBatchResponseEnvelope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBatchResponseEnvelope(val *BatchResponseEnvelope) *NullableBatchResponseEnvelope {
	return &NullableBatchResponseEnvelope{value: val, isSet: true}
}

func (v NullableBatchResponseEnvelope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBatchResponseEnvelope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


