/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.0-preview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the WebhookDeliveriesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookDeliveriesResponse{}

// WebhookDeliveriesResponse Response for webhook deliveries listing.
type WebhookDeliveriesResponse struct {
	Success *bool `json:"success,omitempty"`
	Data map[string]interface{} `json:"data"`
}

type _WebhookDeliveriesResponse WebhookDeliveriesResponse

// NewWebhookDeliveriesResponse instantiates a new WebhookDeliveriesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookDeliveriesResponse(data map[string]interface{}) *WebhookDeliveriesResponse {
	this := WebhookDeliveriesResponse{}
	var success bool = true
	this.Success = &success
	this.Data = data
	return &this
}

// NewWebhookDeliveriesResponseWithDefaults instantiates a new WebhookDeliveriesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookDeliveriesResponseWithDefaults() *WebhookDeliveriesResponse {
	this := WebhookDeliveriesResponse{}
	var success bool = true
	this.Success = &success
	return &this
}

// GetSuccess returns the Success field value if set, zero value otherwise.
func (o *WebhookDeliveriesResponse) GetSuccess() bool {
	if o == nil || IsNil(o.Success) {
		var ret bool
		return ret
	}
	return *o.Success
}

// GetSuccessOk returns a tuple with the Success field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesResponse) GetSuccessOk() (*bool, bool) {
	if o == nil || IsNil(o.Success) {
		return nil, false
	}
	return o.Success, true
}

// HasSuccess returns a boolean if a field has been set.
func (o *WebhookDeliveriesResponse) HasSuccess() bool {
	if o != nil && !IsNil(o.Success) {
		return true
	}

	return false
}

// SetSuccess gets a reference to the given bool and assigns it to the Success field.
func (o *WebhookDeliveriesResponse) SetSuccess(v bool) {
	o.Success = &v
}

// GetData returns the Data field value
func (o *WebhookDeliveriesResponse) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *WebhookDeliveriesResponse) GetDataOk() (map[string]interface{}, bool) {
	if o == nil {
		return map[string]interface{}{}, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *WebhookDeliveriesResponse) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o WebhookDeliveriesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookDeliveriesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Success) {
		toSerialize["success"] = o.Success
	}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *WebhookDeliveriesResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varWebhookDeliveriesResponse := _WebhookDeliveriesResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varWebhookDeliveriesResponse)

	if err != nil {
		return err
	}

	*o = WebhookDeliveriesResponse(varWebhookDeliveriesResponse)

	return err
}

type NullableWebhookDeliveriesResponse struct {
	value *WebhookDeliveriesResponse
	isSet bool
}

func (v NullableWebhookDeliveriesResponse) Get() *WebhookDeliveriesResponse {
	return v.value
}

func (v *NullableWebhookDeliveriesResponse) Set(val *WebhookDeliveriesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookDeliveriesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookDeliveriesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookDeliveriesResponse(val *WebhookDeliveriesResponse) *NullableWebhookDeliveriesResponse {
	return &NullableWebhookDeliveriesResponse{value: val, isSet: true}
}

func (v NullableWebhookDeliveriesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookDeliveriesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


