/*
Encypher Enterprise API

C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

API version: 1.0.0-preview
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package encypher

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DocumentStatusResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DocumentStatusResponse{}

// DocumentStatusResponse Response for document status query.
type DocumentStatusResponse struct {
	DocumentId string `json:"document_id"`
	OrganizationId string `json:"organization_id"`
	Revoked bool `json:"revoked"`
	RevokedAt NullableString `json:"revoked_at,omitempty"`
	RevokedReason NullableString `json:"revoked_reason,omitempty"`
	RevokedReasonDetail NullableString `json:"revoked_reason_detail,omitempty"`
	ReinstatedAt NullableString `json:"reinstated_at,omitempty"`
	StatusListUrl NullableString `json:"status_list_url,omitempty"`
	StatusListIndex NullableInt32 `json:"status_list_index,omitempty"`
	StatusBitIndex NullableInt32 `json:"status_bit_index,omitempty"`
}

type _DocumentStatusResponse DocumentStatusResponse

// NewDocumentStatusResponse instantiates a new DocumentStatusResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDocumentStatusResponse(documentId string, organizationId string, revoked bool) *DocumentStatusResponse {
	this := DocumentStatusResponse{}
	this.DocumentId = documentId
	this.OrganizationId = organizationId
	this.Revoked = revoked
	return &this
}

// NewDocumentStatusResponseWithDefaults instantiates a new DocumentStatusResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDocumentStatusResponseWithDefaults() *DocumentStatusResponse {
	this := DocumentStatusResponse{}
	return &this
}

// GetDocumentId returns the DocumentId field value
func (o *DocumentStatusResponse) GetDocumentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DocumentId
}

// GetDocumentIdOk returns a tuple with the DocumentId field value
// and a boolean to check if the value has been set.
func (o *DocumentStatusResponse) GetDocumentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DocumentId, true
}

// SetDocumentId sets field value
func (o *DocumentStatusResponse) SetDocumentId(v string) {
	o.DocumentId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *DocumentStatusResponse) GetOrganizationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *DocumentStatusResponse) GetOrganizationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *DocumentStatusResponse) SetOrganizationId(v string) {
	o.OrganizationId = v
}

// GetRevoked returns the Revoked field value
func (o *DocumentStatusResponse) GetRevoked() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Revoked
}

// GetRevokedOk returns a tuple with the Revoked field value
// and a boolean to check if the value has been set.
func (o *DocumentStatusResponse) GetRevokedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Revoked, true
}

// SetRevoked sets field value
func (o *DocumentStatusResponse) SetRevoked(v bool) {
	o.Revoked = v
}

// GetRevokedAt returns the RevokedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetRevokedAt() string {
	if o == nil || IsNil(o.RevokedAt.Get()) {
		var ret string
		return ret
	}
	return *o.RevokedAt.Get()
}

// GetRevokedAtOk returns a tuple with the RevokedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetRevokedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedAt.Get(), o.RevokedAt.IsSet()
}

// HasRevokedAt returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasRevokedAt() bool {
	if o != nil && o.RevokedAt.IsSet() {
		return true
	}

	return false
}

// SetRevokedAt gets a reference to the given NullableString and assigns it to the RevokedAt field.
func (o *DocumentStatusResponse) SetRevokedAt(v string) {
	o.RevokedAt.Set(&v)
}
// SetRevokedAtNil sets the value for RevokedAt to be an explicit nil
func (o *DocumentStatusResponse) SetRevokedAtNil() {
	o.RevokedAt.Set(nil)
}

// UnsetRevokedAt ensures that no value is present for RevokedAt, not even an explicit nil
func (o *DocumentStatusResponse) UnsetRevokedAt() {
	o.RevokedAt.Unset()
}

// GetRevokedReason returns the RevokedReason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetRevokedReason() string {
	if o == nil || IsNil(o.RevokedReason.Get()) {
		var ret string
		return ret
	}
	return *o.RevokedReason.Get()
}

// GetRevokedReasonOk returns a tuple with the RevokedReason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetRevokedReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedReason.Get(), o.RevokedReason.IsSet()
}

// HasRevokedReason returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasRevokedReason() bool {
	if o != nil && o.RevokedReason.IsSet() {
		return true
	}

	return false
}

// SetRevokedReason gets a reference to the given NullableString and assigns it to the RevokedReason field.
func (o *DocumentStatusResponse) SetRevokedReason(v string) {
	o.RevokedReason.Set(&v)
}
// SetRevokedReasonNil sets the value for RevokedReason to be an explicit nil
func (o *DocumentStatusResponse) SetRevokedReasonNil() {
	o.RevokedReason.Set(nil)
}

// UnsetRevokedReason ensures that no value is present for RevokedReason, not even an explicit nil
func (o *DocumentStatusResponse) UnsetRevokedReason() {
	o.RevokedReason.Unset()
}

// GetRevokedReasonDetail returns the RevokedReasonDetail field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetRevokedReasonDetail() string {
	if o == nil || IsNil(o.RevokedReasonDetail.Get()) {
		var ret string
		return ret
	}
	return *o.RevokedReasonDetail.Get()
}

// GetRevokedReasonDetailOk returns a tuple with the RevokedReasonDetail field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetRevokedReasonDetailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RevokedReasonDetail.Get(), o.RevokedReasonDetail.IsSet()
}

// HasRevokedReasonDetail returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasRevokedReasonDetail() bool {
	if o != nil && o.RevokedReasonDetail.IsSet() {
		return true
	}

	return false
}

// SetRevokedReasonDetail gets a reference to the given NullableString and assigns it to the RevokedReasonDetail field.
func (o *DocumentStatusResponse) SetRevokedReasonDetail(v string) {
	o.RevokedReasonDetail.Set(&v)
}
// SetRevokedReasonDetailNil sets the value for RevokedReasonDetail to be an explicit nil
func (o *DocumentStatusResponse) SetRevokedReasonDetailNil() {
	o.RevokedReasonDetail.Set(nil)
}

// UnsetRevokedReasonDetail ensures that no value is present for RevokedReasonDetail, not even an explicit nil
func (o *DocumentStatusResponse) UnsetRevokedReasonDetail() {
	o.RevokedReasonDetail.Unset()
}

// GetReinstatedAt returns the ReinstatedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetReinstatedAt() string {
	if o == nil || IsNil(o.ReinstatedAt.Get()) {
		var ret string
		return ret
	}
	return *o.ReinstatedAt.Get()
}

// GetReinstatedAtOk returns a tuple with the ReinstatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetReinstatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReinstatedAt.Get(), o.ReinstatedAt.IsSet()
}

// HasReinstatedAt returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasReinstatedAt() bool {
	if o != nil && o.ReinstatedAt.IsSet() {
		return true
	}

	return false
}

// SetReinstatedAt gets a reference to the given NullableString and assigns it to the ReinstatedAt field.
func (o *DocumentStatusResponse) SetReinstatedAt(v string) {
	o.ReinstatedAt.Set(&v)
}
// SetReinstatedAtNil sets the value for ReinstatedAt to be an explicit nil
func (o *DocumentStatusResponse) SetReinstatedAtNil() {
	o.ReinstatedAt.Set(nil)
}

// UnsetReinstatedAt ensures that no value is present for ReinstatedAt, not even an explicit nil
func (o *DocumentStatusResponse) UnsetReinstatedAt() {
	o.ReinstatedAt.Unset()
}

// GetStatusListUrl returns the StatusListUrl field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetStatusListUrl() string {
	if o == nil || IsNil(o.StatusListUrl.Get()) {
		var ret string
		return ret
	}
	return *o.StatusListUrl.Get()
}

// GetStatusListUrlOk returns a tuple with the StatusListUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetStatusListUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusListUrl.Get(), o.StatusListUrl.IsSet()
}

// HasStatusListUrl returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasStatusListUrl() bool {
	if o != nil && o.StatusListUrl.IsSet() {
		return true
	}

	return false
}

// SetStatusListUrl gets a reference to the given NullableString and assigns it to the StatusListUrl field.
func (o *DocumentStatusResponse) SetStatusListUrl(v string) {
	o.StatusListUrl.Set(&v)
}
// SetStatusListUrlNil sets the value for StatusListUrl to be an explicit nil
func (o *DocumentStatusResponse) SetStatusListUrlNil() {
	o.StatusListUrl.Set(nil)
}

// UnsetStatusListUrl ensures that no value is present for StatusListUrl, not even an explicit nil
func (o *DocumentStatusResponse) UnsetStatusListUrl() {
	o.StatusListUrl.Unset()
}

// GetStatusListIndex returns the StatusListIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetStatusListIndex() int32 {
	if o == nil || IsNil(o.StatusListIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.StatusListIndex.Get()
}

// GetStatusListIndexOk returns a tuple with the StatusListIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetStatusListIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusListIndex.Get(), o.StatusListIndex.IsSet()
}

// HasStatusListIndex returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasStatusListIndex() bool {
	if o != nil && o.StatusListIndex.IsSet() {
		return true
	}

	return false
}

// SetStatusListIndex gets a reference to the given NullableInt32 and assigns it to the StatusListIndex field.
func (o *DocumentStatusResponse) SetStatusListIndex(v int32) {
	o.StatusListIndex.Set(&v)
}
// SetStatusListIndexNil sets the value for StatusListIndex to be an explicit nil
func (o *DocumentStatusResponse) SetStatusListIndexNil() {
	o.StatusListIndex.Set(nil)
}

// UnsetStatusListIndex ensures that no value is present for StatusListIndex, not even an explicit nil
func (o *DocumentStatusResponse) UnsetStatusListIndex() {
	o.StatusListIndex.Unset()
}

// GetStatusBitIndex returns the StatusBitIndex field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *DocumentStatusResponse) GetStatusBitIndex() int32 {
	if o == nil || IsNil(o.StatusBitIndex.Get()) {
		var ret int32
		return ret
	}
	return *o.StatusBitIndex.Get()
}

// GetStatusBitIndexOk returns a tuple with the StatusBitIndex field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *DocumentStatusResponse) GetStatusBitIndexOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.StatusBitIndex.Get(), o.StatusBitIndex.IsSet()
}

// HasStatusBitIndex returns a boolean if a field has been set.
func (o *DocumentStatusResponse) HasStatusBitIndex() bool {
	if o != nil && o.StatusBitIndex.IsSet() {
		return true
	}

	return false
}

// SetStatusBitIndex gets a reference to the given NullableInt32 and assigns it to the StatusBitIndex field.
func (o *DocumentStatusResponse) SetStatusBitIndex(v int32) {
	o.StatusBitIndex.Set(&v)
}
// SetStatusBitIndexNil sets the value for StatusBitIndex to be an explicit nil
func (o *DocumentStatusResponse) SetStatusBitIndexNil() {
	o.StatusBitIndex.Set(nil)
}

// UnsetStatusBitIndex ensures that no value is present for StatusBitIndex, not even an explicit nil
func (o *DocumentStatusResponse) UnsetStatusBitIndex() {
	o.StatusBitIndex.Unset()
}

func (o DocumentStatusResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DocumentStatusResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["document_id"] = o.DocumentId
	toSerialize["organization_id"] = o.OrganizationId
	toSerialize["revoked"] = o.Revoked
	if o.RevokedAt.IsSet() {
		toSerialize["revoked_at"] = o.RevokedAt.Get()
	}
	if o.RevokedReason.IsSet() {
		toSerialize["revoked_reason"] = o.RevokedReason.Get()
	}
	if o.RevokedReasonDetail.IsSet() {
		toSerialize["revoked_reason_detail"] = o.RevokedReasonDetail.Get()
	}
	if o.ReinstatedAt.IsSet() {
		toSerialize["reinstated_at"] = o.ReinstatedAt.Get()
	}
	if o.StatusListUrl.IsSet() {
		toSerialize["status_list_url"] = o.StatusListUrl.Get()
	}
	if o.StatusListIndex.IsSet() {
		toSerialize["status_list_index"] = o.StatusListIndex.Get()
	}
	if o.StatusBitIndex.IsSet() {
		toSerialize["status_bit_index"] = o.StatusBitIndex.Get()
	}
	return toSerialize, nil
}

func (o *DocumentStatusResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"document_id",
		"organization_id",
		"revoked",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDocumentStatusResponse := _DocumentStatusResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDocumentStatusResponse)

	if err != nil {
		return err
	}

	*o = DocumentStatusResponse(varDocumentStatusResponse)

	return err
}

type NullableDocumentStatusResponse struct {
	value *DocumentStatusResponse
	isSet bool
}

func (v NullableDocumentStatusResponse) Get() *DocumentStatusResponse {
	return v.value
}

func (v *NullableDocumentStatusResponse) Set(val *DocumentStatusResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDocumentStatusResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDocumentStatusResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDocumentStatusResponse(val *DocumentStatusResponse) *NullableDocumentStatusResponse {
	return &NullableDocumentStatusResponse{value: val, isSet: true}
}

func (v NullableDocumentStatusResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDocumentStatusResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


