/* tslint:disable */
/* eslint-disable */
/**
 * Encypher Enterprise API
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BatchItemPayload } from './BatchItemPayload';
import {
    BatchItemPayloadFromJSON,
    BatchItemPayloadFromJSONTyped,
    BatchItemPayloadToJSON,
    BatchItemPayloadToJSONTyped,
} from './BatchItemPayload';

/**
 * Batch verification request (shares schema for now).
 * @export
 * @interface AppSchemasBatchBatchVerifyRequest
 */
export interface AppSchemasBatchBatchVerifyRequest {
    /**
     * Processing mode: 'c2pa' or 'embeddings'
     * @type {string}
     * @memberof AppSchemasBatchBatchVerifyRequest
     */
    mode: AppSchemasBatchBatchVerifyRequestModeEnum;
    /**
     * 
     * @type {string}
     * @memberof AppSchemasBatchBatchVerifyRequest
     */
    segmentationLevel?: AppSchemasBatchBatchVerifyRequestSegmentationLevelEnum | null;
    /**
     * Caller-supplied key used to deduplicate retries
     * @type {string}
     * @memberof AppSchemasBatchBatchVerifyRequest
     */
    idempotencyKey: string;
    /**
     * Documents to process (max 100)
     * @type {Array<BatchItemPayload>}
     * @memberof AppSchemasBatchBatchVerifyRequest
     */
    items: Array<BatchItemPayload>;
    /**
     * Abort remaining items upon the first error when set to true
     * @type {boolean}
     * @memberof AppSchemasBatchBatchVerifyRequest
     */
    failFast?: boolean;
}


/**
 * @export
 */
export const AppSchemasBatchBatchVerifyRequestModeEnum = {
    C2pa: 'c2pa',
    Embeddings: 'embeddings'
} as const;
export type AppSchemasBatchBatchVerifyRequestModeEnum = typeof AppSchemasBatchBatchVerifyRequestModeEnum[keyof typeof AppSchemasBatchBatchVerifyRequestModeEnum];

/**
 * @export
 */
export const AppSchemasBatchBatchVerifyRequestSegmentationLevelEnum = {
    Document: 'document',
    Paragraph: 'paragraph',
    Sentence: 'sentence'
} as const;
export type AppSchemasBatchBatchVerifyRequestSegmentationLevelEnum = typeof AppSchemasBatchBatchVerifyRequestSegmentationLevelEnum[keyof typeof AppSchemasBatchBatchVerifyRequestSegmentationLevelEnum];


/**
 * Check if a given object implements the AppSchemasBatchBatchVerifyRequest interface.
 */
export function instanceOfAppSchemasBatchBatchVerifyRequest(value: object): value is AppSchemasBatchBatchVerifyRequest {
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('idempotencyKey' in value) || value['idempotencyKey'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    return true;
}

export function AppSchemasBatchBatchVerifyRequestFromJSON(json: any): AppSchemasBatchBatchVerifyRequest {
    return AppSchemasBatchBatchVerifyRequestFromJSONTyped(json, false);
}

export function AppSchemasBatchBatchVerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasBatchBatchVerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mode': json['mode'],
        'segmentationLevel': json['segmentation_level'] == null ? undefined : json['segmentation_level'],
        'idempotencyKey': json['idempotency_key'],
        'items': ((json['items'] as Array<any>).map(BatchItemPayloadFromJSON)),
        'failFast': json['fail_fast'] == null ? undefined : json['fail_fast'],
    };
}

export function AppSchemasBatchBatchVerifyRequestToJSON(json: any): AppSchemasBatchBatchVerifyRequest {
    return AppSchemasBatchBatchVerifyRequestToJSONTyped(json, false);
}

export function AppSchemasBatchBatchVerifyRequestToJSONTyped(value?: AppSchemasBatchBatchVerifyRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mode': value['mode'],
        'segmentation_level': value['segmentationLevel'],
        'idempotency_key': value['idempotencyKey'],
        'items': ((value['items'] as Array<any>).map(BatchItemPayloadToJSON)),
        'fail_fast': value['failFast'],
    };
}

