/* tslint:disable */
/* eslint-disable */
/**
 * Encypher Enterprise API
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Schema for complete document verification
 * @export
 * @interface DocumentVerify
 */
export interface DocumentVerify {
    /**
     * 
     * @type {string}
     * @memberof DocumentVerify
     */
    documentId: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentVerify
     */
    content: string;
}

/**
 * Check if a given object implements the DocumentVerify interface.
 */
export function instanceOfDocumentVerify(value: object): value is DocumentVerify {
    if (!('documentId' in value) || value['documentId'] === undefined) return false;
    if (!('content' in value) || value['content'] === undefined) return false;
    return true;
}

export function DocumentVerifyFromJSON(json: any): DocumentVerify {
    return DocumentVerifyFromJSONTyped(json, false);
}

export function DocumentVerifyFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentVerify {
    if (json == null) {
        return json;
    }
    return {
        
        'documentId': json['document_id'],
        'content': json['content'],
    };
}

export function DocumentVerifyToJSON(json: any): DocumentVerify {
    return DocumentVerifyToJSONTyped(json, false);
}

export function DocumentVerifyToJSONTyped(value?: DocumentVerify | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'document_id': value['documentId'],
        'content': value['content'],
    };
}

