/* tslint:disable */
/* eslint-disable */
/**
 * Encypher Enterprise API
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentDetail } from './DocumentDetail';
import {
    DocumentDetailFromJSON,
    DocumentDetailFromJSONTyped,
    DocumentDetailToJSON,
    DocumentDetailToJSONTyped,
} from './DocumentDetail';

/**
 * Response for single document.
 * @export
 * @interface DocumentDetailResponse
 */
export interface DocumentDetailResponse {
    /**
     * 
     * @type {boolean}
     * @memberof DocumentDetailResponse
     */
    success?: boolean;
    /**
     * 
     * @type {DocumentDetail}
     * @memberof DocumentDetailResponse
     */
    data: DocumentDetail;
}

/**
 * Check if a given object implements the DocumentDetailResponse interface.
 */
export function instanceOfDocumentDetailResponse(value: object): value is DocumentDetailResponse {
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function DocumentDetailResponseFromJSON(json: any): DocumentDetailResponse {
    return DocumentDetailResponseFromJSONTyped(json, false);
}

export function DocumentDetailResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentDetailResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'data': DocumentDetailFromJSON(json['data']),
    };
}

export function DocumentDetailResponseToJSON(json: any): DocumentDetailResponse {
    return DocumentDetailResponseToJSONTyped(json, false);
}

export function DocumentDetailResponseToJSONTyped(value?: DocumentDetailResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': DocumentDetailToJSON(value['data']),
    };
}

