/* tslint:disable */
/* eslint-disable */
/**
 * Encypher Enterprise API
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request schema for finding source documents.
 * @export
 * @interface SourceAttributionRequest
 */
export interface SourceAttributionRequest {
    /**
     * Text segment to search for
     * @type {string}
     * @memberof SourceAttributionRequest
     */
    textSegment: string;
    /**
     * Segmentation level to search at
     * @type {string}
     * @memberof SourceAttributionRequest
     */
    segmentationLevel?: string;
    /**
     * Whether to normalize text before hashing
     * @type {boolean}
     * @memberof SourceAttributionRequest
     */
    normalize?: boolean;
    /**
     * Whether to include Merkle proof in response
     * @type {boolean}
     * @memberof SourceAttributionRequest
     */
    includeProof?: boolean;
}

/**
 * Check if a given object implements the SourceAttributionRequest interface.
 */
export function instanceOfSourceAttributionRequest(value: object): value is SourceAttributionRequest {
    if (!('textSegment' in value) || value['textSegment'] === undefined) return false;
    return true;
}

export function SourceAttributionRequestFromJSON(json: any): SourceAttributionRequest {
    return SourceAttributionRequestFromJSONTyped(json, false);
}

export function SourceAttributionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceAttributionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'textSegment': json['text_segment'],
        'segmentationLevel': json['segmentation_level'] == null ? undefined : json['segmentation_level'],
        'normalize': json['normalize'] == null ? undefined : json['normalize'],
        'includeProof': json['include_proof'] == null ? undefined : json['include_proof'],
    };
}

export function SourceAttributionRequestToJSON(json: any): SourceAttributionRequest {
    return SourceAttributionRequestToJSONTyped(json, false);
}

export function SourceAttributionRequestToJSONTyped(value?: SourceAttributionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'text_segment': value['textSegment'],
        'segmentation_level': value['segmentationLevel'],
        'normalize': value['normalize'],
        'include_proof': value['includeProof'],
    };
}

