# coding: utf-8

"""
    Encypher Enterprise API

    C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises

    The version of the OpenAPI document: 1.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class StreamMerkleFinalizeRequest(BaseModel):
    """
    Request to finalize a streaming Merkle session and compute the final root.  This completes the tree construction, computes the final root hash, and optionally embeds a C2PA manifest into the full document.
    """ # noqa: E501
    session_id: StrictStr = Field(description="Session ID to finalize")
    embed_manifest: Optional[StrictBool] = Field(default=True, description="Whether to embed C2PA manifest into the final document")
    manifest_mode: Optional[StrictStr] = Field(default='full', description="Manifest mode: full or micro")
    action: Optional[StrictStr] = Field(default='c2pa.created', description="C2PA action type: c2pa.created or c2pa.edited")
    __properties: ClassVar[List[str]] = ["session_id", "embed_manifest", "manifest_mode", "action"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StreamMerkleFinalizeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StreamMerkleFinalizeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "session_id": obj.get("session_id"),
            "embed_manifest": obj.get("embed_manifest") if obj.get("embed_manifest") is not None else True,
            "manifest_mode": obj.get("manifest_mode") if obj.get("manifest_mode") is not None else 'full',
            "action": obj.get("action") if obj.get("action") is not None else 'c2pa.created'
        })
        return _obj
