/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AppSchemasMerkleErrorResponse : Standard error response schema.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AppSchemasMerkleErrorResponse {
    /// Always false for errors
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    /// Error type
    #[serde(rename = "error")]
    pub error: String,
    /// Human-readable error message
    #[serde(rename = "message")]
    pub message: String,
    #[serde(rename = "details", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub details: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl AppSchemasMerkleErrorResponse {
    /// Standard error response schema.
    pub fn new(error: String, message: String) -> AppSchemasMerkleErrorResponse {
        AppSchemasMerkleErrorResponse {
            success: None,
            error,
            message,
            details: None,
        }
    }
}

