/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchItemPayload : Single document payload within a batch request.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchItemPayload {
    /// Unique document identifier
    #[serde(rename = "document_id")]
    pub document_id: String,
    /// Raw document text to process
    #[serde(rename = "text")]
    pub text: String,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
}

impl BatchItemPayload {
    /// Single document payload within a batch request.
    pub fn new(document_id: String, text: String) -> BatchItemPayload {
        BatchItemPayload {
            document_id,
            text,
            title: None,
            metadata: None,
        }
    }
}

