/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BatchVerifyRequest : Batch verification request (shares schema for now).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BatchVerifyRequest {
    /// Processing mode: 'c2pa' or 'embeddings'
    #[serde(rename = "mode")]
    pub mode: Mode,
    #[serde(rename = "segmentation_level", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub segmentation_level: Option<Option<SegmentationLevel>>,
    /// Caller-supplied key used to deduplicate retries
    #[serde(rename = "idempotency_key")]
    pub idempotency_key: String,
    /// Documents to process (max 100)
    #[serde(rename = "items")]
    pub items: Vec<models::BatchItemPayload>,
    /// Abort remaining items upon the first error when set to true
    #[serde(rename = "fail_fast", skip_serializing_if = "Option::is_none")]
    pub fail_fast: Option<bool>,
}

impl BatchVerifyRequest {
    /// Batch verification request (shares schema for now).
    pub fn new(mode: Mode, idempotency_key: String, items: Vec<models::BatchItemPayload>) -> BatchVerifyRequest {
        BatchVerifyRequest {
            mode,
            segmentation_level: None,
            idempotency_key,
            items,
            fail_fast: None,
        }
    }
}
/// Processing mode: 'c2pa' or 'embeddings'
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Mode {
    #[serde(rename = "c2pa")]
    C2pa,
    #[serde(rename = "embeddings")]
    Embeddings,
}

impl Default for Mode {
    fn default() -> Mode {
        Self::C2pa
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SegmentationLevel {
    #[serde(rename = "document")]
    Document,
    #[serde(rename = "paragraph")]
    Paragraph,
    #[serde(rename = "sentence")]
    Sentence,
}

impl Default for SegmentationLevel {
    fn default() -> SegmentationLevel {
        Self::Document
    }
}

