/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DocumentStatusResponse : Response for document status query.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentStatusResponse {
    #[serde(rename = "document_id")]
    pub document_id: String,
    #[serde(rename = "organization_id")]
    pub organization_id: String,
    #[serde(rename = "revoked")]
    pub revoked: bool,
    #[serde(rename = "revoked_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_at: Option<Option<String>>,
    #[serde(rename = "revoked_reason", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_reason: Option<Option<String>>,
    #[serde(rename = "revoked_reason_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revoked_reason_detail: Option<Option<String>>,
    #[serde(rename = "reinstated_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub reinstated_at: Option<Option<String>>,
    #[serde(rename = "status_list_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_list_url: Option<Option<String>>,
    #[serde(rename = "status_list_index", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_list_index: Option<Option<i32>>,
    #[serde(rename = "status_bit_index", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status_bit_index: Option<Option<i32>>,
}

impl DocumentStatusResponse {
    /// Response for document status query.
    pub fn new(document_id: String, organization_id: String, revoked: bool) -> DocumentStatusResponse {
        DocumentStatusResponse {
            document_id,
            organization_id,
            revoked,
            revoked_at: None,
            revoked_reason: None,
            revoked_reason_detail: None,
            reinstated_at: None,
            status_list_url: None,
            status_list_index: None,
            status_bit_index: None,
        }
    }
}

