/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DocumentInfo : Document information from verification.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DocumentInfo {
    /// Document identifier
    #[serde(rename = "document_id")]
    pub document_id: String,
    #[serde(rename = "title", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub title: Option<Option<String>>,
    #[serde(rename = "published_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<Option<String>>,
    #[serde(rename = "author", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author: Option<Option<String>>,
    /// Organization name
    #[serde(rename = "organization")]
    pub organization: String,
}

impl DocumentInfo {
    /// Document information from verification.
    pub fn new(document_id: String, organization: String) -> DocumentInfo {
        DocumentInfo {
            document_id,
            title: None,
            published_at: None,
            author: None,
            organization,
        }
    }
}

