/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// KeyRevokeResponse : Response after revoking a key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KeyRevokeResponse {
    #[serde(rename = "success", skip_serializing_if = "Option::is_none")]
    pub success: Option<bool>,
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, serde_json::Value>,
}

impl KeyRevokeResponse {
    /// Response after revoking a key.
    pub fn new(data: std::collections::HashMap<String, serde_json::Value>) -> KeyRevokeResponse {
        KeyRevokeResponse {
            success: None,
            data,
        }
    }
}

