/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SignResponse : Response model for signing operation.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SignResponse {
    /// Whether the operation was successful
    #[serde(rename = "success")]
    pub success: bool,
    /// Unique document identifier
    #[serde(rename = "document_id")]
    pub document_id: String,
    /// Text with embedded C2PA manifest
    #[serde(rename = "signed_text")]
    pub signed_text: String,
    /// Number of sentences signed
    #[serde(rename = "total_sentences")]
    pub total_sentences: i32,
    /// URL for public verification
    #[serde(rename = "verification_url")]
    pub verification_url: String,
}

impl SignResponse {
    /// Response model for signing operation.
    pub fn new(success: bool, document_id: String, signed_text: String, total_sentences: i32, verification_url: String) -> SignResponse {
        SignResponse {
            success,
            document_id,
            signed_text,
            total_sentences,
            verification_url,
        }
    }
}

