/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VerifyEmbeddingRequest : Request to verify an embedding (for batch operations).
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyEmbeddingRequest {
    /// Reference ID (8 hex characters)
    #[serde(rename = "ref_id")]
    pub ref_id: String,
    /// Signature (8+ hex characters)
    #[serde(rename = "signature")]
    pub signature: String,
}

impl VerifyEmbeddingRequest {
    /// Request to verify an embedding (for batch operations).
    pub fn new(ref_id: String, signature: String) -> VerifyEmbeddingRequest {
        VerifyEmbeddingRequest {
            ref_id,
            signature,
        }
    }
}

