/*
 * Encypher Enterprise API
 *
 * C2PA-compliant content signing and verification infrastructure for publishers, legal/finance firms, AI labs, and enterprises
 *
 * The version of the OpenAPI document: 1.0.0-preview
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// WebhookUpdateRequest : Request to update a webhook.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WebhookUpdateRequest {
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "events", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub events: Option<Option<Vec<String>>>,
    #[serde(rename = "is_active", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_active: Option<Option<bool>>,
}

impl WebhookUpdateRequest {
    /// Request to update a webhook.
    pub fn new() -> WebhookUpdateRequest {
        WebhookUpdateRequest {
            url: None,
            events: None,
            is_active: None,
        }
    }
}

