import {
  buildSignAdvancedRequest,
  buildSignBasicRequest,
  mapVerifyResponseToDecodeToolResponse,
} from "./enterpriseApiTools";

describe("enterpriseApiTools", () => {
  it("buildSignAdvancedRequest maps encode payload to /sign/advanced request", () => {
    const req = buildSignAdvancedRequest({
      original_text: "hello world",
      metadata_format: "c2pa_v2_2",
      ai_info: {
        claim_generator: "Encypher Demo UI",
        provenance: "Generated by an AI",
      },
    });

    expect(req.text).toBe("hello world");
    expect(req.segmentation_level).toBe("sentence");
    expect(req.action).toBe("c2pa.created");
    expect(req.metadata).toEqual(
      expect.objectContaining({
        claim_generator: "Encypher Demo UI",
        provenance: "Generated by an AI",
      })
    );
  });

  it("buildSignBasicRequest maps encode payload to /sign request", () => {
    const req = buildSignBasicRequest({
      original_text: "hello world",
      custom_metadata: { campaign: "winter" },
      ai_info: {
        claim_generator: "Encypher Marketing Site",
        provenance: "Marketing tool",
      },
    });

    expect(req.text).toBe("hello world");
    expect(req.action).toBe("c2pa.created");
    expect(req.metadata).toEqual({ campaign: "winter" });
    expect(req.custom_assertions).toEqual([
      {
        label: "c2pa.generative-ai",
        data: {
          softwareAgent: "Encypher Marketing Site",
          description: "Marketing tool",
        },
      },
    ]);
  });

  it("mapVerifyResponseToDecodeToolResponse converts /verify response to legacy decode shape", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-1",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "VERIFIED",
        signer_id: "org_demo",
        signer_name: "Demo",
        timestamp: null,
        details: { manifest: { instance_id: "abc" } },
        embeddings_found: 1,
        all_embeddings: null,
      },
    });

    expect(decoded.verification_status).toBe("Success");
    expect(decoded.embeddings_found).toBe(1);
    expect(decoded.raw_hidden_data?.valid).toBe(true);
    expect(decoded.metadata).toEqual({ manifest: { instance_id: "abc" } });
  });
});
