import {
  buildSignAdvancedRequest,
  buildSignBasicRequest,
  mapVerifyResponseToDecodeToolResponse,
} from "./enterpriseApiTools";

describe("enterpriseApiTools", () => {
  it("buildSignAdvancedRequest maps encode payload to unified /sign request with options", () => {
    const req = buildSignAdvancedRequest({
      original_text: "hello world",
      metadata_format: "c2pa_v2_2",
      ai_info: {
        claim_generator: "Encypher Demo UI",
        provenance: "Generated by an AI",
      },
    });

    expect(req.text).toBe("hello world");
    expect(req.options?.segmentation_level).toBe("sentence");
    expect(req.options?.action).toBe("c2pa.created");
    expect(req.metadata).toEqual(
      expect.objectContaining({
        claim_generator: "Encypher Demo UI",
        provenance: "Generated by an AI",
      })
    );
  });

  it("buildSignBasicRequest maps encode payload to unified /sign request", () => {
    const req = buildSignBasicRequest({
      original_text: "hello world",
      custom_metadata: { campaign: "winter" },
      ai_info: {
        provenance: "Marketing tool",
      },
    });

    expect(req.text).toBe("hello world");
    expect(req.options?.action).toBe("c2pa.created");
    expect(req.metadata).toEqual({ campaign: "winter" });
    expect(req.options?.custom_assertions).toEqual([
      {
        label: "org.encypher.user-provenance",
        data: {
          text: "Marketing tool",
        },
      },
    ]);
  });

  it("mapVerifyResponseToDecodeToolResponse converts /verify response to legacy decode shape", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-1",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "VERIFIED",
        signer_id: "org_demo",
        signer_name: "Demo",
        timestamp: null,
        details: { manifest: { instance_id: "abc" } },
        embeddings_found: 1,
        all_embeddings: null,
      },
    });

    expect(decoded.verification_status).toBe("Success");
    expect(decoded.embeddings_found).toBe(1);
    expect(decoded.raw_hidden_data?.valid).toBe(true);
    expect(decoded.metadata).toEqual({ manifest: { instance_id: "abc" } });
  });

  it("mapVerifyResponseToDecodeToolResponse passes through segment_embeddings and total_segments_in_document", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-2",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "OK",
        signer_id: "org_test",
        details: { manifest: { segment_uuid: "uuid-1", total_signatures: 2 } },
        embeddings_found: 2,
        all_embeddings: null,
        embeddings: [
          {
            segment_uuid: "uuid-1",
            leaf_index: 3,
            segment_location: { paragraph_index: 0, sentence_in_paragraph: 0 },
            manifest_mode: "micro_ecc_c2pa",
          },
          {
            segment_uuid: "uuid-2",
            leaf_index: 4,
            segment_location: { paragraph_index: 0, sentence_in_paragraph: 1 },
            manifest_mode: "micro_ecc_c2pa",
          },
        ],
        total_embeddings: 2,
        total_segments_in_document: 10,
        c2pa: null,
      },
    });

    expect(decoded.segment_embeddings).toHaveLength(2);
    expect(decoded.segment_embeddings![0].segment_uuid).toBe("uuid-1");
    expect(decoded.segment_embeddings![0].segment_location).toEqual({
      paragraph_index: 0,
      sentence_in_paragraph: 0,
    });
    expect(decoded.segment_embeddings![0].leaf_index).toBe(3);
    expect(decoded.segment_embeddings![0].manifest_mode).toBe("micro_ecc_c2pa");
    expect(decoded.segment_embeddings![1].segment_uuid).toBe("uuid-2");
    expect(decoded.segment_embeddings![1].segment_location).toEqual({
      paragraph_index: 0,
      sentence_in_paragraph: 1,
    });
    expect(decoded.total_segments_in_document).toBe(10);
  });

  it("mapVerifyResponseToDecodeToolResponse passes through c2pa manifest info", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-3",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "OK",
        signer_id: "org_c2pa",
        details: { manifest: { segment_uuid: "uuid-c2pa", total_signatures: 1 } },
        embeddings_found: 1,
        all_embeddings: null,
        embeddings: [
          {
            segment_uuid: "uuid-c2pa",
            manifest_mode: "micro_ecc_c2pa",
          },
        ],
        total_embeddings: 1,
        total_segments_in_document: 5,
        c2pa: {
          validated: true,
          validation_type: "db_backed_manifest",
          manifest_hash: "hash123",
          assertions: [{ label: "c2pa.actions" }],
        },
      },
    });

    expect(decoded.c2pa).toBeDefined();
    expect(decoded.c2pa!.validated).toBe(true);
    expect(decoded.c2pa!.validation_type).toBe("db_backed_manifest");
    expect(decoded.c2pa!.manifest_hash).toBe("hash123");
    expect(decoded.c2pa!.assertions).toHaveLength(1);
  });

  it("mapVerifyResponseToDecodeToolResponse prefers total_embeddings for embeddings_found count", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-5",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "OK",
        signer_id: "org_test",
        details: { manifest: { segment_uuid: "uuid-1", total_signatures: 13 } },
        all_embeddings: null,
        embeddings: [
          { segment_uuid: "uuid-1", manifest_mode: "micro_ecc_c2pa" },
          { segment_uuid: "uuid-2", manifest_mode: "micro_ecc_c2pa" },
          { segment_uuid: "uuid-3", manifest_mode: "micro_ecc_c2pa" },
        ],
        total_embeddings: 3,
        total_segments_in_document: 27,
      },
    });

    expect(decoded.embeddings_found).toBe(3);
    expect(decoded.total_segments_in_document).toBe(27);
  });

  it("mapVerifyResponseToDecodeToolResponse returns null for missing segment fields", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-4",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "OK",
        details: { manifest: { segment_uuid: "uuid-zw", total_signatures: 1 } },
        embeddings_found: 1,
        all_embeddings: null,
      },
    });

    expect(decoded.segment_embeddings).toBeNull();
    expect(decoded.total_segments_in_document).toBeNull();
    expect(decoded.c2pa).toBeNull();
  });

  it("mapVerifyResponseToDecodeToolResponse resolves signer label from manifest when signer_name is unavailable", () => {
    const decoded = mapVerifyResponseToDecodeToolResponse({
      success: true,
      correlation_id: "req-6",
      error: null,
      data: {
        valid: true,
        tampered: false,
        reason_code: "OK",
        signer_id: "org_abc123",
        signer_name: "org_abc123",
        details: {
          manifest: {
            custom_metadata: {
              publisher_name: "Encypher Newsroom",
            },
          },
        },
        embeddings_found: 1,
        all_embeddings: null,
      },
    });

    expect(decoded.raw_hidden_data?.signer_name).toBe("Encypher Newsroom");
    expect(decoded.raw_hidden_data?.signer_id).toBe("org_abc123");
  });
});
