export const PLAYGROUND_ENDPOINTS = [
  {
    id: 'sign',
    name: 'Sign Content',
    method: 'POST',
    path: '/sign',
    description: 'Sign text with invisible C2PA provenance. We recommend sentence-level segmentation so each sentence gets its own signature — if someone edits one sentence, you can pinpoint exactly which one changed.',
    category: 'Signing',
    requiresAuth: true,
    authType: 'both',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        text: 'Scientists at CERN have detected high-energy particles originating from a distant galaxy. The discovery could reshape our understanding of cosmic ray propagation. Researchers plan to publish their findings in Nature next month.',
        document_title: 'CERN Cosmic Ray Discovery',
        options: {
          document_type: 'article',
          segmentation_level: 'sentence',
          manifest_mode: 'micro',
        },
      },
      null,
      2
    ),
  },
  {
    id: 'verify',
    name: 'Verify Content',
    method: 'POST',
    path: '/verify',
    description: 'Verify signed content — checks who signed it, when, and whether it has been tampered with. Paste the signed text exactly as received (invisible signatures travel with the text). Works without authentication; pass an API key for richer results.',
    category: 'Verification',
    requiresAuth: false,
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        text: 'Paste signed content here to verify...',
      },
      null,
      2
    ),
  },
  {
    id: 'lookup',
    name: 'Lookup Sentence',
    method: 'POST',
    path: '/lookup',
    description: 'Lookup sentence provenance (public).',
    category: 'Verification',
    requiresAuth: false,
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        sentence_text: 'The Senate passed a landmark bill today.',
      },
      null,
      2
    ),
  },
  {
    id: 'verify-advanced',
    name: 'Verify Content (Advanced)',
    method: 'POST',
    path: '/verify/advanced',
    description: 'Advanced verification with enriched provenance and policy diagnostics.',
    category: 'Verification',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        text: 'Paste signed content here to verify with advanced diagnostics...',
      },
      null,
      2
    ),
  },
  {
    id: 'stream-sign',
    name: 'Stream Sign (SSE)',
    method: 'POST',
    path: '/sign/stream',
    description: 'Stream signing progress via Server-Sent Events.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        text: 'Streaming content to sign...',
        document_title: 'Streaming Example',
        document_type: 'article',
      },
      null,
      2
    ),
  },
  {
    id: 'stream-chat-openai',
    name: 'Stream Chat (OpenAI Compatible)',
    method: 'POST',
    path: '/chat/completions',
    description: 'OpenAI-compatible streaming chat with signed response.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        model: 'gpt-3.5-turbo',
        stream: true,
        sign_response: true,
        messages: [
          {
            role: 'user',
            content: 'Summarize the latest C2PA guidelines in one paragraph.',
          },
        ],
      },
      null,
      2
    ),
  },
  {
    id: 'stream-chat-health',
    name: 'Stream Chat Health',
    method: 'GET',
    path: '/chat/health',
    description: 'Health check for chat streaming (public).',
    category: 'Streaming',
    requiresAuth: false,
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'stream-events',
    name: 'Stream Events (SSE)',
    method: 'GET',
    path: '/sign/stream/sessions/{session_id}/events',
    description: 'Subscribe to streaming events for a session.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'stream-session-create',
    name: 'Stream Session Create',
    method: 'POST',
    path: '/sign/stream/sessions',
    description: 'Create a streaming session.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        session_type: 'websocket',
        metadata: {
          source: 'playground',
        },
        signing_options: {
          manifest_mode: 'full',
        },
      },
      null,
      2
    ),
  },
  {
    id: 'stream-session-close',
    name: 'Stream Session Close',
    method: 'POST',
    path: '/sign/stream/sessions/{session_id}/close',
    description: 'Close a streaming session.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'stream-runs',
    name: 'Stream Run Status',
    method: 'GET',
    path: '/sign/stream/runs/{run_id}',
    description: 'Fetch streaming run state.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'stream-stats',
    name: 'Stream Stats',
    method: 'GET',
    path: '/sign/stream/stats',
    description: 'Streaming usage statistics.',
    category: 'Streaming',
    requiresAuth: true,
    authType: 'both',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'status-document',
    name: 'Get Document Status',
    method: 'GET',
    path: '/status/documents/{document_id}',
    description: 'Check revocation status for a document.',
    category: 'Status & Revocation',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'status-revoke',
    name: 'Revoke Document',
    method: 'POST',
    path: '/status/documents/{document_id}/revoke',
    description: 'Revoke a signed document.',
    category: 'Status & Revocation',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
    sampleBody: JSON.stringify(
      {
        reason: 'factual_error',
        reason_detail: 'Optional details about the revocation.',
      },
      null,
      2
    ),
  },
  {
    id: 'status-reinstate',
    name: 'Reinstate Document',
    method: 'POST',
    path: '/status/documents/{document_id}/reinstate',
    description: 'Reinstate a revoked document.',
    category: 'Status & Revocation',
    requiresAuth: true,
    authType: 'both',
    minTier: 'enterprise',
    docsUrl: 'https://api.encypher.com/docs',
  },
  {
    id: 'status-list',
    name: 'Get Status List',
    method: 'GET',
    path: '/status/list/{organization_id}/{list_index}',
    description: 'Fetch a W3C StatusList2021 credential (public).',
    category: 'Status & Revocation',
    requiresAuth: false,
    docsUrl: 'https://api.encypher.com/docs',
  },
];
