#!/usr/bin/env python3
"""C2PA External Ingestion Evidence Generator.

Walks the c2pa_sample_library directory and verifies every media file using
the c2pa-python Reader, producing per-file and consolidated JSON evidence.
This demonstrates that our verification pipeline can ingest and validate C2PA
manifests generated by third-party conformance products (Google Pixel Camera,
Google Photos, Google NotebookLM).

Run from enterprise_api/:
    uv run python tests/c2pa_conformance/run_external_ingestion.py
"""

import io
import json
import logging
import os
import sys
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

# Ensure enterprise_api app package is importable when run from enterprise_api/
sys.path.insert(0, ".")

logging.basicConfig(level=logging.INFO, format="%(message)s")
log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

_THIS_DIR = Path(__file__).resolve().parent
SAMPLE_LIBRARY_DIR = _THIS_DIR / "c2pa_sample_library"
EVIDENCE_DIR = _THIS_DIR / "external_ingestion_evidence"

# ---------------------------------------------------------------------------
# MIME type mapping (extension -> MIME)
# ---------------------------------------------------------------------------

EXT_TO_MIME: dict[str, str] = {
    ".jpg": "image/jpeg",
    ".jpeg": "image/jpeg",
    ".png": "image/png",
    ".webp": "image/webp",
    ".tiff": "image/tiff",
    ".avif": "image/avif",
    ".heic": "image/heic",
    ".heif": "image/heif",
    ".mp4": "video/mp4",
    ".mov": "video/quicktime",
    ".wav": "audio/wav",
    ".mp3": "audio/mpeg",
    ".m4a": "audio/mp4",
}

# Extensions to skip entirely (metadata sidecars, not media)
SKIP_EXTENSIONS: frozenset[str] = frozenset(
    {
        ".json",
        ".txtpb",
        ".txt",
        ".md",
    }
)


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------


@dataclass
class ExternalIngestionRecord:
    filename: str
    source: str  # subfolder name (e.g. "Pixel Camera Prod")
    mime_type: str
    has_manifest: bool
    valid: Optional[bool]  # None when no manifest present
    manifest_summary: Optional[dict]
    error: Optional[str]


# ---------------------------------------------------------------------------
# Verification helper
# ---------------------------------------------------------------------------


def _verify_with_c2pa_reader(
    data: bytes,
    mime_type: str,
    is_stripped: bool,
) -> tuple[bool, Optional[bool], Optional[dict], Optional[str]]:
    """Run c2pa.Reader on file bytes.

    Returns (has_manifest, valid, manifest_summary, error).
    """
    import c2pa

    try:
        reader = c2pa.Reader(mime_type, io.BytesIO(data))
        manifest_json = reader.json()
        reader.close()

        manifest_data = json.loads(manifest_json) if manifest_json else {}

        active_label = manifest_data.get("active_manifest", "")
        manifests = manifest_data.get("manifests", {})
        active = manifests.get(active_label, {}) if active_label else {}

        if not active_label or not active:
            # No manifest found -- expected for stripped files
            return False, None, None, None

        claim_generator = active.get("claim_generator", "")
        assertion_count = len(active.get("assertions", []))

        # Signer from certificate or claim
        signer: Optional[str] = None
        credentials = active.get("credentials", [])
        if credentials:
            cert = credentials[0]
            subject = cert.get("subject", {})
            # DER-decoded certs have an 'organization' or 'common_name' field
            signer = subject.get("organization") or subject.get("common_name") or subject.get("organizationName")

        # Assess validity -- ignore informational credential/trust failures
        vr = manifest_data.get("validation_results", {})
        active_vr = vr.get("activeManifest", {})
        INFORMATIONAL = {
            "signingCredential.untrusted",
            "signingCredential.expired",
            "timeStamp.untrusted",
        }
        structural_failures = [f for f in active_vr.get("failure", []) if isinstance(f, dict) and f.get("code") not in INFORMATIONAL]
        valid = len(structural_failures) == 0

        # Derive a human-readable validation_status string
        if valid:
            info_count = len([f for f in active_vr.get("failure", []) if isinstance(f, dict) and f.get("code") in INFORMATIONAL])
            validation_status = f"valid (with {info_count} informational notice(s))" if info_count else "valid"
        else:
            codes = [f.get("code", "unknown") for f in structural_failures if isinstance(f, dict)]
            validation_status = f"invalid: {', '.join(codes)}"

        summary = {
            "claim_generator": claim_generator,
            "signer": signer,
            "validation_status": validation_status,
            "assertion_count": assertion_count,
            "active_manifest_label": active_label,
            "success_checks": len(active_vr.get("success", [])),
            "failure_count": len(structural_failures),
            "informational_failures": len([f for f in active_vr.get("failure", []) if isinstance(f, dict) and f.get("code") in INFORMATIONAL]),
        }

        return True, valid, summary, None

    except Exception as exc:
        err = str(exc)
        # For stripped files, "no manifest" errors are expected
        if is_stripped and ("no manifest" in err.lower() or "not found" in err.lower() or "manifest store" in err.lower()):
            return False, None, None, None
        return False, False, None, err


# ---------------------------------------------------------------------------
# Walk helper
# ---------------------------------------------------------------------------


def _source_name(filepath: Path) -> str:
    """Return the immediate subdirectory under c2pa_sample_library as the source name.

    For files nested under 'Interoperability Testing Files/Photos Prod/...'
    we return 'Photos Prod'. For files nested directly we return the top-level
    subdir name.
    """
    # Compute relative path from SAMPLE_LIBRARY_DIR
    try:
        rel = filepath.relative_to(SAMPLE_LIBRARY_DIR)
    except ValueError:
        return "unknown"
    parts = rel.parts
    # parts[0] may be "Interoperability Testing Files" -- skip that wrapper if present
    if len(parts) >= 3 and parts[0].lower().startswith("interoperability"):
        return parts[1]
    if len(parts) >= 2:
        return parts[0]
    return "root"


def collect_media_files(root: Path) -> list[Path]:
    """Walk root recursively and return all media files, sorted."""
    media: list[Path] = []
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        ext = path.suffix.lower()
        if ext in SKIP_EXTENSIONS:
            continue
        if ext in EXT_TO_MIME:
            media.append(path)
        # Unknown extensions: skip silently
    return media


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------


def run() -> None:
    """Process all media files in the sample library."""
    EVIDENCE_DIR.mkdir(parents=True, exist_ok=True)

    # Clear stale per-file evidence from previous runs
    for stale in EVIDENCE_DIR.glob("*_evidence.json"):
        stale.unlink()

    timestamp = datetime.now(timezone.utc).isoformat()
    records: list[ExternalIngestionRecord] = []

    media_files = collect_media_files(SAMPLE_LIBRARY_DIR)
    log.info(f"Found {len(media_files)} media files in {SAMPLE_LIBRARY_DIR.name}/")
    log.info("")

    for filepath in media_files:
        ext = filepath.suffix.lower()
        mime_type = EXT_TO_MIME[ext]
        source = _source_name(filepath)
        is_stripped = "_stripped" in filepath.name.lower()

        log.info(f"  [{source}] {filepath.name}")

        file_bytes = filepath.read_bytes()
        has_manifest, valid, manifest_summary, error = _verify_with_c2pa_reader(file_bytes, mime_type, is_stripped)

        if not has_manifest and is_stripped:
            status_msg = "no manifest (stripped -- expected)"
        elif not has_manifest:
            status_msg = "no manifest found"
        elif valid:
            gen = (manifest_summary or {}).get("claim_generator", "")[:60]
            status_msg = f"VALID -- generator: {gen or '(present)'}"
        else:
            status_msg = f"INVALID -- {error or (manifest_summary or {}).get('validation_status', '')}"

        log.info(f"    -> {status_msg}")

        record = ExternalIngestionRecord(
            filename=filepath.name,
            source=source,
            mime_type=mime_type,
            has_manifest=has_manifest,
            valid=valid,
            manifest_summary=manifest_summary,
            error=error,
        )
        records.append(record)

        # Per-file evidence JSON -- use source+stem to avoid collisions
        safe_source = source.replace(" ", "_").replace("/", "_")
        safe_stem = filepath.stem.replace(" ", "_")
        evidence_filename = f"{safe_source}__{safe_stem}_evidence.json"
        with open(EVIDENCE_DIR / evidence_filename, "w") as f:
            json.dump(asdict(record), f, indent=2)

    # ---------------------------------------------------------------------------
    # Consolidated summary
    # ---------------------------------------------------------------------------

    files_with_manifest = [r for r in records if r.has_manifest]
    valid_count = sum(1 for r in records if r.valid is True)
    invalid_count = sum(1 for r in records if r.valid is False)
    no_manifest_count = sum(1 for r in records if r.valid is None)

    summary = {
        "generated_at": timestamp,
        "sample_library": str(SAMPLE_LIBRARY_DIR),
        "total_files": len(records),
        "files_with_manifest": len(files_with_manifest),
        "files_without_manifest": no_manifest_count,
        "valid_count": valid_count,
        "invalid_count": invalid_count,
        "results": [asdict(r) for r in records],
    }

    results_path = EVIDENCE_DIR / "external_ingestion_results.json"
    with open(results_path, "w") as f:
        json.dump(summary, f, indent=2)

    # ---------------------------------------------------------------------------
    # Summary table
    # ---------------------------------------------------------------------------

    log.info("")
    log.info("=" * 90)
    log.info(f"{'Source':<30} {'Filename':<45} {'Manifest':<10} {'Valid'}")
    log.info("-" * 90)
    for r in records:
        has = "YES" if r.has_manifest else "no"
        if r.valid is True:
            valid_str = "PASS"
        elif r.valid is False:
            valid_str = f"FAIL ({r.error or r.manifest_summary or ''})"[:30]
        else:
            valid_str = "n/a (stripped)" if "_stripped" in r.filename.lower() else "n/a"
        log.info(f"{r.source:<30} {r.filename:<45} {has:<10} {valid_str}")

    log.info("=" * 90)
    log.info(f"Total files:           {len(records)}")
    log.info(f"  With C2PA manifest:  {len(files_with_manifest)}")
    log.info(f"    Valid:             {valid_count}")
    log.info(f"    Invalid:           {invalid_count}")
    log.info(f"  No manifest:         {no_manifest_count}")
    log.info(f"Output: {EVIDENCE_DIR}/")
    log.info("  external_ingestion_results.json  (consolidated)")
    log.info("  <source>__<name>_evidence.json   (per-file)")


if __name__ == "__main__":
    # Change to enterprise_api/ so relative imports resolve
    os.chdir(Path(__file__).resolve().parents[2])
    run()
